package com.gts.expersoft.models;
// Generated Jan 10, 2018 12:00:18 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Acces generated by hbm2java
 */
public class Acces implements java.io.Serializable {

	private int id;
	private Profile profile;
	private String login;
	private String password;
	private Set utilisateurs = new HashSet(0);

	public Acces() {
	}

	public Acces(int id, Profile profile) {
		this.id = id;
		this.profile = profile;
	}

	public Acces(int id, Profile profile, String login, String password, Set utilisateurs) {
		this.id = id;
		this.profile = profile;
		this.login = login;
		this.password = password;
		this.utilisateurs = utilisateurs;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
