package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Banque generated by hbm2java
 */
public class Banque implements java.io.Serializable {

	private BanqueId id;

	public Banque() {
	}

	public Banque(BanqueId id) {
		this.id = id;
	}

	public BanqueId getId() {
		return this.id;
	}

	public void setId(BanqueId id) {
		this.id = id;
	}

}
