package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * BanqueId generated by hbm2java
 */
public class BanqueId implements java.io.Serializable {

	private String codBq;
	private String libBq;
	private String compte;
	private String gestion;
	private String etatImp;
	private Double mtLimit;
	private String nocptBq;
	private String adrBq;
	private String telBq;
	private String faxBq;
	private String importe;
	private Integer codCaut;
	private Integer codLetr;
	private String chqConf;
	private Integer chroJou;
	private String codIban;
	private String codSwift;
	private String repCau;
	private Integer typBq;
	private String comptBq;
	private String foncGest;
	private String telGest;
	private Integer mtSeuil;
	private String iban;
	private String swift;

	public BanqueId() {
	}

	public BanqueId(String codBq, String libBq, String compte, String gestion, String etatImp, Double mtLimit,
			String nocptBq, String adrBq, String telBq, String faxBq, String importe, Integer codCaut, Integer codLetr,
			String chqConf, Integer chroJou, String codIban, String codSwift, String repCau, Integer typBq,
			String comptBq, String foncGest, String telGest, Integer mtSeuil, String iban, String swift) {
		this.codBq = codBq;
		this.libBq = libBq;
		this.compte = compte;
		this.gestion = gestion;
		this.etatImp = etatImp;
		this.mtLimit = mtLimit;
		this.nocptBq = nocptBq;
		this.adrBq = adrBq;
		this.telBq = telBq;
		this.faxBq = faxBq;
		this.importe = importe;
		this.codCaut = codCaut;
		this.codLetr = codLetr;
		this.chqConf = chqConf;
		this.chroJou = chroJou;
		this.codIban = codIban;
		this.codSwift = codSwift;
		this.repCau = repCau;
		this.typBq = typBq;
		this.comptBq = comptBq;
		this.foncGest = foncGest;
		this.telGest = telGest;
		this.mtSeuil = mtSeuil;
		this.iban = iban;
		this.swift = swift;
	}

	public String getCodBq() {
		return this.codBq;
	}

	public void setCodBq(String codBq) {
		this.codBq = codBq;
	}

	public String getLibBq() {
		return this.libBq;
	}

	public void setLibBq(String libBq) {
		this.libBq = libBq;
	}

	public String getCompte() {
		return this.compte;
	}

	public void setCompte(String compte) {
		this.compte = compte;
	}

	public String getGestion() {
		return this.gestion;
	}

	public void setGestion(String gestion) {
		this.gestion = gestion;
	}

	public String getEtatImp() {
		return this.etatImp;
	}

	public void setEtatImp(String etatImp) {
		this.etatImp = etatImp;
	}

	public Double getMtLimit() {
		return this.mtLimit;
	}

	public void setMtLimit(Double mtLimit) {
		this.mtLimit = mtLimit;
	}

	public String getNocptBq() {
		return this.nocptBq;
	}

	public void setNocptBq(String nocptBq) {
		this.nocptBq = nocptBq;
	}

	public String getAdrBq() {
		return this.adrBq;
	}

	public void setAdrBq(String adrBq) {
		this.adrBq = adrBq;
	}

	public String getTelBq() {
		return this.telBq;
	}

	public void setTelBq(String telBq) {
		this.telBq = telBq;
	}

	public String getFaxBq() {
		return this.faxBq;
	}

	public void setFaxBq(String faxBq) {
		this.faxBq = faxBq;
	}

	public String getImporte() {
		return this.importe;
	}

	public void setImporte(String importe) {
		this.importe = importe;
	}

	public Integer getCodCaut() {
		return this.codCaut;
	}

	public void setCodCaut(Integer codCaut) {
		this.codCaut = codCaut;
	}

	public Integer getCodLetr() {
		return this.codLetr;
	}

	public void setCodLetr(Integer codLetr) {
		this.codLetr = codLetr;
	}

	public String getChqConf() {
		return this.chqConf;
	}

	public void setChqConf(String chqConf) {
		this.chqConf = chqConf;
	}

	public Integer getChroJou() {
		return this.chroJou;
	}

	public void setChroJou(Integer chroJou) {
		this.chroJou = chroJou;
	}

	public String getCodIban() {
		return this.codIban;
	}

	public void setCodIban(String codIban) {
		this.codIban = codIban;
	}

	public String getCodSwift() {
		return this.codSwift;
	}

	public void setCodSwift(String codSwift) {
		this.codSwift = codSwift;
	}

	public String getRepCau() {
		return this.repCau;
	}

	public void setRepCau(String repCau) {
		this.repCau = repCau;
	}

	public Integer getTypBq() {
		return this.typBq;
	}

	public void setTypBq(Integer typBq) {
		this.typBq = typBq;
	}

	public String getComptBq() {
		return this.comptBq;
	}

	public void setComptBq(String comptBq) {
		this.comptBq = comptBq;
	}

	public String getFoncGest() {
		return this.foncGest;
	}

	public void setFoncGest(String foncGest) {
		this.foncGest = foncGest;
	}

	public String getTelGest() {
		return this.telGest;
	}

	public void setTelGest(String telGest) {
		this.telGest = telGest;
	}

	public Integer getMtSeuil() {
		return this.mtSeuil;
	}

	public void setMtSeuil(Integer mtSeuil) {
		this.mtSeuil = mtSeuil;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getSwift() {
		return this.swift;
	}

	public void setSwift(String swift) {
		this.swift = swift;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BanqueId))
			return false;
		BanqueId castOther = (BanqueId) other;

		return ((this.getCodBq() == castOther.getCodBq()) || (this.getCodBq() != null && castOther.getCodBq() != null
				&& this.getCodBq().equals(castOther.getCodBq())))
				&& ((this.getLibBq() == castOther.getLibBq()) || (this.getLibBq() != null
						&& castOther.getLibBq() != null && this.getLibBq().equals(castOther.getLibBq())))
				&& ((this.getCompte() == castOther.getCompte()) || (this.getCompte() != null
						&& castOther.getCompte() != null && this.getCompte().equals(castOther.getCompte())))
				&& ((this.getGestion() == castOther.getGestion()) || (this.getGestion() != null
						&& castOther.getGestion() != null && this.getGestion().equals(castOther.getGestion())))
				&& ((this.getEtatImp() == castOther.getEtatImp()) || (this.getEtatImp() != null
						&& castOther.getEtatImp() != null && this.getEtatImp().equals(castOther.getEtatImp())))
				&& ((this.getMtLimit() == castOther.getMtLimit()) || (this.getMtLimit() != null
						&& castOther.getMtLimit() != null && this.getMtLimit().equals(castOther.getMtLimit())))
				&& ((this.getNocptBq() == castOther.getNocptBq()) || (this.getNocptBq() != null
						&& castOther.getNocptBq() != null && this.getNocptBq().equals(castOther.getNocptBq())))
				&& ((this.getAdrBq() == castOther.getAdrBq()) || (this.getAdrBq() != null
						&& castOther.getAdrBq() != null && this.getAdrBq().equals(castOther.getAdrBq())))
				&& ((this.getTelBq() == castOther.getTelBq()) || (this.getTelBq() != null
						&& castOther.getTelBq() != null && this.getTelBq().equals(castOther.getTelBq())))
				&& ((this.getFaxBq() == castOther.getFaxBq()) || (this.getFaxBq() != null
						&& castOther.getFaxBq() != null && this.getFaxBq().equals(castOther.getFaxBq())))
				&& ((this.getImporte() == castOther.getImporte()) || (this.getImporte() != null
						&& castOther.getImporte() != null && this.getImporte().equals(castOther.getImporte())))
				&& ((this.getCodCaut() == castOther.getCodCaut()) || (this.getCodCaut() != null
						&& castOther.getCodCaut() != null && this.getCodCaut().equals(castOther.getCodCaut())))
				&& ((this.getCodLetr() == castOther.getCodLetr()) || (this.getCodLetr() != null
						&& castOther.getCodLetr() != null && this.getCodLetr().equals(castOther.getCodLetr())))
				&& ((this.getChqConf() == castOther.getChqConf()) || (this.getChqConf() != null
						&& castOther.getChqConf() != null && this.getChqConf().equals(castOther.getChqConf())))
				&& ((this.getChroJou() == castOther.getChroJou()) || (this.getChroJou() != null
						&& castOther.getChroJou() != null && this.getChroJou().equals(castOther.getChroJou())))
				&& ((this.getCodIban() == castOther.getCodIban()) || (this.getCodIban() != null
						&& castOther.getCodIban() != null && this.getCodIban().equals(castOther.getCodIban())))
				&& ((this.getCodSwift() == castOther.getCodSwift()) || (this.getCodSwift() != null
						&& castOther.getCodSwift() != null && this.getCodSwift().equals(castOther.getCodSwift())))
				&& ((this.getRepCau() == castOther.getRepCau()) || (this.getRepCau() != null
						&& castOther.getRepCau() != null && this.getRepCau().equals(castOther.getRepCau())))
				&& ((this.getTypBq() == castOther.getTypBq()) || (this.getTypBq() != null
						&& castOther.getTypBq() != null && this.getTypBq().equals(castOther.getTypBq())))
				&& ((this.getComptBq() == castOther.getComptBq()) || (this.getComptBq() != null
						&& castOther.getComptBq() != null && this.getComptBq().equals(castOther.getComptBq())))
				&& ((this.getFoncGest() == castOther.getFoncGest()) || (this.getFoncGest() != null
						&& castOther.getFoncGest() != null && this.getFoncGest().equals(castOther.getFoncGest())))
				&& ((this.getTelGest() == castOther.getTelGest()) || (this.getTelGest() != null
						&& castOther.getTelGest() != null && this.getTelGest().equals(castOther.getTelGest())))
				&& ((this.getMtSeuil() == castOther.getMtSeuil()) || (this.getMtSeuil() != null
						&& castOther.getMtSeuil() != null && this.getMtSeuil().equals(castOther.getMtSeuil())))
				&& ((this.getIban() == castOther.getIban()) || (this.getIban() != null && castOther.getIban() != null
						&& this.getIban().equals(castOther.getIban())))
				&& ((this.getSwift() == castOther.getSwift()) || (this.getSwift() != null
						&& castOther.getSwift() != null && this.getSwift().equals(castOther.getSwift())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodBq() == null ? 0 : this.getCodBq().hashCode());
		result = 37 * result + (getLibBq() == null ? 0 : this.getLibBq().hashCode());
		result = 37 * result + (getCompte() == null ? 0 : this.getCompte().hashCode());
		result = 37 * result + (getGestion() == null ? 0 : this.getGestion().hashCode());
		result = 37 * result + (getEtatImp() == null ? 0 : this.getEtatImp().hashCode());
		result = 37 * result + (getMtLimit() == null ? 0 : this.getMtLimit().hashCode());
		result = 37 * result + (getNocptBq() == null ? 0 : this.getNocptBq().hashCode());
		result = 37 * result + (getAdrBq() == null ? 0 : this.getAdrBq().hashCode());
		result = 37 * result + (getTelBq() == null ? 0 : this.getTelBq().hashCode());
		result = 37 * result + (getFaxBq() == null ? 0 : this.getFaxBq().hashCode());
		result = 37 * result + (getImporte() == null ? 0 : this.getImporte().hashCode());
		result = 37 * result + (getCodCaut() == null ? 0 : this.getCodCaut().hashCode());
		result = 37 * result + (getCodLetr() == null ? 0 : this.getCodLetr().hashCode());
		result = 37 * result + (getChqConf() == null ? 0 : this.getChqConf().hashCode());
		result = 37 * result + (getChroJou() == null ? 0 : this.getChroJou().hashCode());
		result = 37 * result + (getCodIban() == null ? 0 : this.getCodIban().hashCode());
		result = 37 * result + (getCodSwift() == null ? 0 : this.getCodSwift().hashCode());
		result = 37 * result + (getRepCau() == null ? 0 : this.getRepCau().hashCode());
		result = 37 * result + (getTypBq() == null ? 0 : this.getTypBq().hashCode());
		result = 37 * result + (getComptBq() == null ? 0 : this.getComptBq().hashCode());
		result = 37 * result + (getFoncGest() == null ? 0 : this.getFoncGest().hashCode());
		result = 37 * result + (getTelGest() == null ? 0 : this.getTelGest().hashCode());
		result = 37 * result + (getMtSeuil() == null ? 0 : this.getMtSeuil().hashCode());
		result = 37 * result + (getIban() == null ? 0 : this.getIban().hashCode());
		result = 37 * result + (getSwift() == null ? 0 : this.getSwift().hashCode());
		return result;
	}

}
