package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * BeId generated by hbm2java
 */
public class Be implements java.io.Serializable {

	private Integer nobe;
	private String datbe;
	private String raisonFou;
	private Integer poidnet;
	private String connais;
	private String codFou;
	private String codUom;
	private Double tareSac;
	private String codProd;
	private String camion;
	private String remorq;
	private Integer poiddec;
	private Integer ecartPoid;
	private String codMag;
	private String codStat;
	private String matPers;
	private String chauffeur;
	private Integer decision;
	private String dateAdd;
	private String dateEdit;
	private String codUtVal;
	private String dateValid;
	private String timeValid;
	private String codTrans;
	private String noCont;
	private Double qte1;
	private Double qte2;
	private Double qte3;
	private Double qtet;
	private Double mt1;
	private Double mt2;
	private Double mt3;
	private Integer montant;
	private String datdeb;
	private String datfin;
	private String codQ1;
	private String codQ2;
	private String libQ1;
	private String libQ2;
	private String codEquip;
	private String codVar;
	private String codFarm;
	private String nomFarm;
	private String codParcel;
	private String codVil;
	private String libVil;
	private String libVar;
	private Double puFarm;
	private Double puFou;
	private Double montfarm;
	private Integer refbe;
	private String datcond;
	private String codCal1;
	private Double qteCal1;
	private String codCal2;
	private Double qteCal2;
	private String codCal3;
	private Double qteCal3;
	private String codCal4;
	private Double qteCal4;
	private String codCal5;
	private Double qteCal5;
	private String codCal6;
	private Double qteCal6;
	private String codCal7;
	private Double qteCal7;
	private String codCal8;
	private Double qteCal8;
	private String codCal9;
	private Double qteCal9;
	private String codCal10;
	private Double qteCal10;
	private String codCal11;
	private Double qteCal11;
	private String codCal12;
	private Double qteCal12;
	private Double qteTore;
	private Double qteNtore;
	private Double qteSpoid;
	private Double qteTot;

	public Be() {
	}

	public Be(Integer nobe, String datbe, String raisonFou, Integer poidnet, String connais, String codFou,
			String codUom, Double tareSac, String codProd, String camion, String remorq, Integer poiddec,
			Integer ecartPoid, String codMag, String codStat, String matPers, String chauffeur, Integer decision,
			String dateAdd, String dateEdit, String codUtVal, String dateValid, String timeValid, String codTrans,
			String noCont, Double qte1, Double qte2, Double qte3, Double qtet, Double mt1, Double mt2, Double mt3,
			Integer montant, String datdeb, String datfin, String codQ1, String codQ2, String libQ1, String libQ2,
			String codEquip, String codVar, String codFarm, String nomFarm, String codParcel, String codVil,
			String libVil, String libVar, Double puFarm, Double puFou, Double montfarm, Integer refbe, String datcond,
			String codCal1, Double qteCal1, String codCal2, Double qteCal2, String codCal3, Double qteCal3,
			String codCal4, Double qteCal4, String codCal5, Double qteCal5, String codCal6, Double qteCal6,
			String codCal7, Double qteCal7, String codCal8, Double qteCal8, String codCal9, Double qteCal9,
			String codCal10, Double qteCal10, String codCal11, Double qteCal11, String codCal12, Double qteCal12,
			Double qteTore, Double qteNtore, Double qteSpoid, Double qteTot) {
		this.nobe = nobe;
		this.datbe = datbe;
		this.raisonFou = raisonFou;
		this.poidnet = poidnet;
		this.connais = connais;
		this.codFou = codFou;
		this.codUom = codUom;
		this.tareSac = tareSac;
		this.codProd = codProd;
		this.camion = camion;
		this.remorq = remorq;
		this.poiddec = poiddec;
		this.ecartPoid = ecartPoid;
		this.codMag = codMag;
		this.codStat = codStat;
		this.matPers = matPers;
		this.chauffeur = chauffeur;
		this.decision = decision;
		this.dateAdd = dateAdd;
		this.dateEdit = dateEdit;
		this.codUtVal = codUtVal;
		this.dateValid = dateValid;
		this.timeValid = timeValid;
		this.codTrans = codTrans;
		this.noCont = noCont;
		this.qte1 = qte1;
		this.qte2 = qte2;
		this.qte3 = qte3;
		this.qtet = qtet;
		this.mt1 = mt1;
		this.mt2 = mt2;
		this.mt3 = mt3;
		this.montant = montant;
		this.datdeb = datdeb;
		this.datfin = datfin;
		this.codQ1 = codQ1;
		this.codQ2 = codQ2;
		this.libQ1 = libQ1;
		this.libQ2 = libQ2;
		this.codEquip = codEquip;
		this.codVar = codVar;
		this.codFarm = codFarm;
		this.nomFarm = nomFarm;
		this.codParcel = codParcel;
		this.codVil = codVil;
		this.libVil = libVil;
		this.libVar = libVar;
		this.puFarm = puFarm;
		this.puFou = puFou;
		this.montfarm = montfarm;
		this.refbe = refbe;
		this.datcond = datcond;
		this.codCal1 = codCal1;
		this.qteCal1 = qteCal1;
		this.codCal2 = codCal2;
		this.qteCal2 = qteCal2;
		this.codCal3 = codCal3;
		this.qteCal3 = qteCal3;
		this.codCal4 = codCal4;
		this.qteCal4 = qteCal4;
		this.codCal5 = codCal5;
		this.qteCal5 = qteCal5;
		this.codCal6 = codCal6;
		this.qteCal6 = qteCal6;
		this.codCal7 = codCal7;
		this.qteCal7 = qteCal7;
		this.codCal8 = codCal8;
		this.qteCal8 = qteCal8;
		this.codCal9 = codCal9;
		this.qteCal9 = qteCal9;
		this.codCal10 = codCal10;
		this.qteCal10 = qteCal10;
		this.codCal11 = codCal11;
		this.qteCal11 = qteCal11;
		this.codCal12 = codCal12;
		this.qteCal12 = qteCal12;
		this.qteTore = qteTore;
		this.qteNtore = qteNtore;
		this.qteSpoid = qteSpoid;
		this.qteTot = qteTot;
	}

	public Integer getNobe() {
		return this.nobe;
	}

	public void setNobe(Integer nobe) {
		this.nobe = nobe;
	}

	public String getDatbe() {
		return this.datbe;
	}

	public void setDatbe(String datbe) {
		this.datbe = datbe;
	}

	public String getRaisonFou() {
		return this.raisonFou;
	}

	public void setRaisonFou(String raisonFou) {
		this.raisonFou = raisonFou;
	}

	public Integer getPoidnet() {
		return this.poidnet;
	}

	public void setPoidnet(Integer poidnet) {
		this.poidnet = poidnet;
	}

	public String getConnais() {
		return this.connais;
	}

	public void setConnais(String connais) {
		this.connais = connais;
	}

	public String getCodFou() {
		return this.codFou;
	}

	public void setCodFou(String codFou) {
		this.codFou = codFou;
	}

	public String getCodUom() {
		return this.codUom;
	}

	public void setCodUom(String codUom) {
		this.codUom = codUom;
	}

	public Double getTareSac() {
		return this.tareSac;
	}

	public void setTareSac(Double tareSac) {
		this.tareSac = tareSac;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public String getCamion() {
		return this.camion;
	}

	public void setCamion(String camion) {
		this.camion = camion;
	}

	public String getRemorq() {
		return this.remorq;
	}

	public void setRemorq(String remorq) {
		this.remorq = remorq;
	}

	public Integer getPoiddec() {
		return this.poiddec;
	}

	public void setPoiddec(Integer poiddec) {
		this.poiddec = poiddec;
	}

	public Integer getEcartPoid() {
		return this.ecartPoid;
	}

	public void setEcartPoid(Integer ecartPoid) {
		this.ecartPoid = ecartPoid;
	}

	public String getCodMag() {
		return this.codMag;
	}

	public void setCodMag(String codMag) {
		this.codMag = codMag;
	}

	public String getCodStat() {
		return this.codStat;
	}

	public void setCodStat(String codStat) {
		this.codStat = codStat;
	}

	public String getMatPers() {
		return this.matPers;
	}

	public void setMatPers(String matPers) {
		this.matPers = matPers;
	}

	public String getChauffeur() {
		return this.chauffeur;
	}

	public void setChauffeur(String chauffeur) {
		this.chauffeur = chauffeur;
	}

	public Integer getDecision() {
		return this.decision;
	}

	public void setDecision(Integer decision) {
		this.decision = decision;
	}

	public String getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(String dateAdd) {
		this.dateAdd = dateAdd;
	}

	public String getDateEdit() {
		return this.dateEdit;
	}

	public void setDateEdit(String dateEdit) {
		this.dateEdit = dateEdit;
	}

	public String getCodUtVal() {
		return this.codUtVal;
	}

	public void setCodUtVal(String codUtVal) {
		this.codUtVal = codUtVal;
	}

	public String getDateValid() {
		return this.dateValid;
	}

	public void setDateValid(String dateValid) {
		this.dateValid = dateValid;
	}

	public String getTimeValid() {
		return this.timeValid;
	}

	public void setTimeValid(String timeValid) {
		this.timeValid = timeValid;
	}

	public String getCodTrans() {
		return this.codTrans;
	}

	public void setCodTrans(String codTrans) {
		this.codTrans = codTrans;
	}

	public String getNoCont() {
		return this.noCont;
	}

	public void setNoCont(String noCont) {
		this.noCont = noCont;
	}

	public Double getQte1() {
		return this.qte1;
	}

	public void setQte1(Double qte1) {
		this.qte1 = qte1;
	}

	public Double getQte2() {
		return this.qte2;
	}

	public void setQte2(Double qte2) {
		this.qte2 = qte2;
	}

	public Double getQte3() {
		return this.qte3;
	}

	public void setQte3(Double qte3) {
		this.qte3 = qte3;
	}

	public Double getQtet() {
		return this.qtet;
	}

	public void setQtet(Double qtet) {
		this.qtet = qtet;
	}

	public Double getMt1() {
		return this.mt1;
	}

	public void setMt1(Double mt1) {
		this.mt1 = mt1;
	}

	public Double getMt2() {
		return this.mt2;
	}

	public void setMt2(Double mt2) {
		this.mt2 = mt2;
	}

	public Double getMt3() {
		return this.mt3;
	}

	public void setMt3(Double mt3) {
		this.mt3 = mt3;
	}

	public Integer getMontant() {
		return this.montant;
	}

	public void setMontant(Integer montant) {
		this.montant = montant;
	}

	public String getDatdeb() {
		return this.datdeb;
	}

	public void setDatdeb(String datdeb) {
		this.datdeb = datdeb;
	}

	public String getDatfin() {
		return this.datfin;
	}

	public void setDatfin(String datfin) {
		this.datfin = datfin;
	}

	public String getCodQ1() {
		return this.codQ1;
	}

	public void setCodQ1(String codQ1) {
		this.codQ1 = codQ1;
	}

	public String getCodQ2() {
		return this.codQ2;
	}

	public void setCodQ2(String codQ2) {
		this.codQ2 = codQ2;
	}

	public String getLibQ1() {
		return this.libQ1;
	}

	public void setLibQ1(String libQ1) {
		this.libQ1 = libQ1;
	}

	public String getLibQ2() {
		return this.libQ2;
	}

	public void setLibQ2(String libQ2) {
		this.libQ2 = libQ2;
	}

	public String getCodEquip() {
		return this.codEquip;
	}

	public void setCodEquip(String codEquip) {
		this.codEquip = codEquip;
	}

	public String getCodVar() {
		return this.codVar;
	}

	public void setCodVar(String codVar) {
		this.codVar = codVar;
	}

	public String getCodFarm() {
		return this.codFarm;
	}

	public void setCodFarm(String codFarm) {
		this.codFarm = codFarm;
	}

	public String getNomFarm() {
		return this.nomFarm;
	}

	public void setNomFarm(String nomFarm) {
		this.nomFarm = nomFarm;
	}

	public String getCodParcel() {
		return this.codParcel;
	}

	public void setCodParcel(String codParcel) {
		this.codParcel = codParcel;
	}

	public String getCodVil() {
		return this.codVil;
	}

	public void setCodVil(String codVil) {
		this.codVil = codVil;
	}

	public String getLibVil() {
		return this.libVil;
	}

	public void setLibVil(String libVil) {
		this.libVil = libVil;
	}

	public String getLibVar() {
		return this.libVar;
	}

	public void setLibVar(String libVar) {
		this.libVar = libVar;
	}

	public Double getPuFarm() {
		return this.puFarm;
	}

	public void setPuFarm(Double puFarm) {
		this.puFarm = puFarm;
	}

	public Double getPuFou() {
		return this.puFou;
	}

	public void setPuFou(Double puFou) {
		this.puFou = puFou;
	}

	public Double getMontfarm() {
		return this.montfarm;
	}

	public void setMontfarm(Double montfarm) {
		this.montfarm = montfarm;
	}

	public Integer getRefbe() {
		return this.refbe;
	}

	public void setRefbe(Integer refbe) {
		this.refbe = refbe;
	}

	public String getDatcond() {
		return this.datcond;
	}

	public void setDatcond(String datcond) {
		this.datcond = datcond;
	}

	public String getCodCal1() {
		return this.codCal1;
	}

	public void setCodCal1(String codCal1) {
		this.codCal1 = codCal1;
	}

	public Double getQteCal1() {
		return this.qteCal1;
	}

	public void setQteCal1(Double qteCal1) {
		this.qteCal1 = qteCal1;
	}

	public String getCodCal2() {
		return this.codCal2;
	}

	public void setCodCal2(String codCal2) {
		this.codCal2 = codCal2;
	}

	public Double getQteCal2() {
		return this.qteCal2;
	}

	public void setQteCal2(Double qteCal2) {
		this.qteCal2 = qteCal2;
	}

	public String getCodCal3() {
		return this.codCal3;
	}

	public void setCodCal3(String codCal3) {
		this.codCal3 = codCal3;
	}

	public Double getQteCal3() {
		return this.qteCal3;
	}

	public void setQteCal3(Double qteCal3) {
		this.qteCal3 = qteCal3;
	}

	public String getCodCal4() {
		return this.codCal4;
	}

	public void setCodCal4(String codCal4) {
		this.codCal4 = codCal4;
	}

	public Double getQteCal4() {
		return this.qteCal4;
	}

	public void setQteCal4(Double qteCal4) {
		this.qteCal4 = qteCal4;
	}

	public String getCodCal5() {
		return this.codCal5;
	}

	public void setCodCal5(String codCal5) {
		this.codCal5 = codCal5;
	}

	public Double getQteCal5() {
		return this.qteCal5;
	}

	public void setQteCal5(Double qteCal5) {
		this.qteCal5 = qteCal5;
	}

	public String getCodCal6() {
		return this.codCal6;
	}

	public void setCodCal6(String codCal6) {
		this.codCal6 = codCal6;
	}

	public Double getQteCal6() {
		return this.qteCal6;
	}

	public void setQteCal6(Double qteCal6) {
		this.qteCal6 = qteCal6;
	}

	public String getCodCal7() {
		return this.codCal7;
	}

	public void setCodCal7(String codCal7) {
		this.codCal7 = codCal7;
	}

	public Double getQteCal7() {
		return this.qteCal7;
	}

	public void setQteCal7(Double qteCal7) {
		this.qteCal7 = qteCal7;
	}

	public String getCodCal8() {
		return this.codCal8;
	}

	public void setCodCal8(String codCal8) {
		this.codCal8 = codCal8;
	}

	public Double getQteCal8() {
		return this.qteCal8;
	}

	public void setQteCal8(Double qteCal8) {
		this.qteCal8 = qteCal8;
	}

	public String getCodCal9() {
		return this.codCal9;
	}

	public void setCodCal9(String codCal9) {
		this.codCal9 = codCal9;
	}

	public Double getQteCal9() {
		return this.qteCal9;
	}

	public void setQteCal9(Double qteCal9) {
		this.qteCal9 = qteCal9;
	}

	public String getCodCal10() {
		return this.codCal10;
	}

	public void setCodCal10(String codCal10) {
		this.codCal10 = codCal10;
	}

	public Double getQteCal10() {
		return this.qteCal10;
	}

	public void setQteCal10(Double qteCal10) {
		this.qteCal10 = qteCal10;
	}

	public String getCodCal11() {
		return this.codCal11;
	}

	public void setCodCal11(String codCal11) {
		this.codCal11 = codCal11;
	}

	public Double getQteCal11() {
		return this.qteCal11;
	}

	public void setQteCal11(Double qteCal11) {
		this.qteCal11 = qteCal11;
	}

	public String getCodCal12() {
		return this.codCal12;
	}

	public void setCodCal12(String codCal12) {
		this.codCal12 = codCal12;
	}

	public Double getQteCal12() {
		return this.qteCal12;
	}

	public void setQteCal12(Double qteCal12) {
		this.qteCal12 = qteCal12;
	}

	public Double getQteTore() {
		return this.qteTore;
	}

	public void setQteTore(Double qteTore) {
		this.qteTore = qteTore;
	}

	public Double getQteNtore() {
		return this.qteNtore;
	}

	public void setQteNtore(Double qteNtore) {
		this.qteNtore = qteNtore;
	}

	public Double getQteSpoid() {
		return this.qteSpoid;
	}

	public void setQteSpoid(Double qteSpoid) {
		this.qteSpoid = qteSpoid;
	}

	public Double getQteTot() {
		return this.qteTot;
	}

	public void setQteTot(Double qteTot) {
		this.qteTot = qteTot;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Be))
			return false;
		Be castOther = (Be) other;

		return ((this.getNobe() == castOther.getNobe()) || (this.getNobe() != null && castOther.getNobe() != null
				&& this.getNobe().equals(castOther.getNobe())))
				&& ((this.getDatbe() == castOther.getDatbe()) || (this.getDatbe() != null
						&& castOther.getDatbe() != null && this.getDatbe().equals(castOther.getDatbe())))
				&& ((this.getRaisonFou() == castOther.getRaisonFou()) || (this.getRaisonFou() != null
						&& castOther.getRaisonFou() != null && this.getRaisonFou().equals(castOther.getRaisonFou())))
				&& ((this.getPoidnet() == castOther.getPoidnet()) || (this.getPoidnet() != null
						&& castOther.getPoidnet() != null && this.getPoidnet().equals(castOther.getPoidnet())))
				&& ((this.getConnais() == castOther.getConnais()) || (this.getConnais() != null
						&& castOther.getConnais() != null && this.getConnais().equals(castOther.getConnais())))
				&& ((this.getCodFou() == castOther.getCodFou()) || (this.getCodFou() != null
						&& castOther.getCodFou() != null && this.getCodFou().equals(castOther.getCodFou())))
				&& ((this.getCodUom() == castOther.getCodUom()) || (this.getCodUom() != null
						&& castOther.getCodUom() != null && this.getCodUom().equals(castOther.getCodUom())))
				&& ((this.getTareSac() == castOther.getTareSac()) || (this.getTareSac() != null
						&& castOther.getTareSac() != null && this.getTareSac().equals(castOther.getTareSac())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getCamion() == castOther.getCamion()) || (this.getCamion() != null
						&& castOther.getCamion() != null && this.getCamion().equals(castOther.getCamion())))
				&& ((this.getRemorq() == castOther.getRemorq()) || (this.getRemorq() != null
						&& castOther.getRemorq() != null && this.getRemorq().equals(castOther.getRemorq())))
				&& ((this.getPoiddec() == castOther.getPoiddec()) || (this.getPoiddec() != null
						&& castOther.getPoiddec() != null && this.getPoiddec().equals(castOther.getPoiddec())))
				&& ((this.getEcartPoid() == castOther.getEcartPoid()) || (this.getEcartPoid() != null
						&& castOther.getEcartPoid() != null && this.getEcartPoid().equals(castOther.getEcartPoid())))
				&& ((this.getCodMag() == castOther.getCodMag()) || (this.getCodMag() != null
						&& castOther.getCodMag() != null && this.getCodMag().equals(castOther.getCodMag())))
				&& ((this.getCodStat() == castOther.getCodStat()) || (this.getCodStat() != null
						&& castOther.getCodStat() != null && this.getCodStat().equals(castOther.getCodStat())))
				&& ((this.getMatPers() == castOther.getMatPers()) || (this.getMatPers() != null
						&& castOther.getMatPers() != null && this.getMatPers().equals(castOther.getMatPers())))
				&& ((this.getChauffeur() == castOther.getChauffeur()) || (this.getChauffeur() != null
						&& castOther.getChauffeur() != null && this.getChauffeur().equals(castOther.getChauffeur())))
				&& ((this.getDecision() == castOther.getDecision()) || (this.getDecision() != null
						&& castOther.getDecision() != null && this.getDecision().equals(castOther.getDecision())))
				&& ((this.getDateAdd() == castOther.getDateAdd()) || (this.getDateAdd() != null
						&& castOther.getDateAdd() != null && this.getDateAdd().equals(castOther.getDateAdd())))
				&& ((this.getDateEdit() == castOther.getDateEdit()) || (this.getDateEdit() != null
						&& castOther.getDateEdit() != null && this.getDateEdit().equals(castOther.getDateEdit())))
				&& ((this.getCodUtVal() == castOther.getCodUtVal()) || (this.getCodUtVal() != null
						&& castOther.getCodUtVal() != null && this.getCodUtVal().equals(castOther.getCodUtVal())))
				&& ((this.getDateValid() == castOther.getDateValid()) || (this.getDateValid() != null
						&& castOther.getDateValid() != null && this.getDateValid().equals(castOther.getDateValid())))
				&& ((this.getTimeValid() == castOther.getTimeValid()) || (this.getTimeValid() != null
						&& castOther.getTimeValid() != null && this.getTimeValid().equals(castOther.getTimeValid())))
				&& ((this.getCodTrans() == castOther.getCodTrans()) || (this.getCodTrans() != null
						&& castOther.getCodTrans() != null && this.getCodTrans().equals(castOther.getCodTrans())))
				&& ((this.getNoCont() == castOther.getNoCont()) || (this.getNoCont() != null
						&& castOther.getNoCont() != null && this.getNoCont().equals(castOther.getNoCont())))
				&& ((this.getQte1() == castOther.getQte1()) || (this.getQte1() != null && castOther.getQte1() != null
						&& this.getQte1().equals(castOther.getQte1())))
				&& ((this.getQte2() == castOther.getQte2()) || (this.getQte2() != null && castOther.getQte2() != null
						&& this.getQte2().equals(castOther.getQte2())))
				&& ((this.getQte3() == castOther.getQte3()) || (this.getQte3() != null && castOther.getQte3() != null
						&& this.getQte3().equals(castOther.getQte3())))
				&& ((this.getQtet() == castOther.getQtet()) || (this.getQtet() != null && castOther.getQtet() != null
						&& this.getQtet().equals(castOther.getQtet())))
				&& ((this.getMt1() == castOther.getMt1()) || (this.getMt1() != null && castOther.getMt1() != null
						&& this.getMt1().equals(castOther.getMt1())))
				&& ((this.getMt2() == castOther.getMt2()) || (this.getMt2() != null && castOther.getMt2() != null
						&& this.getMt2().equals(castOther.getMt2())))
				&& ((this.getMt3() == castOther.getMt3()) || (this.getMt3() != null && castOther.getMt3() != null
						&& this.getMt3().equals(castOther.getMt3())))
				&& ((this.getMontant() == castOther.getMontant()) || (this.getMontant() != null
						&& castOther.getMontant() != null && this.getMontant().equals(castOther.getMontant())))
				&& ((this.getDatdeb() == castOther.getDatdeb()) || (this.getDatdeb() != null
						&& castOther.getDatdeb() != null && this.getDatdeb().equals(castOther.getDatdeb())))
				&& ((this.getDatfin() == castOther.getDatfin()) || (this.getDatfin() != null
						&& castOther.getDatfin() != null && this.getDatfin().equals(castOther.getDatfin())))
				&& ((this.getCodQ1() == castOther.getCodQ1()) || (this.getCodQ1() != null
						&& castOther.getCodQ1() != null && this.getCodQ1().equals(castOther.getCodQ1())))
				&& ((this.getCodQ2() == castOther.getCodQ2()) || (this.getCodQ2() != null
						&& castOther.getCodQ2() != null && this.getCodQ2().equals(castOther.getCodQ2())))
				&& ((this.getLibQ1() == castOther.getLibQ1()) || (this.getLibQ1() != null
						&& castOther.getLibQ1() != null && this.getLibQ1().equals(castOther.getLibQ1())))
				&& ((this.getLibQ2() == castOther.getLibQ2()) || (this.getLibQ2() != null
						&& castOther.getLibQ2() != null && this.getLibQ2().equals(castOther.getLibQ2())))
				&& ((this.getCodEquip() == castOther.getCodEquip()) || (this.getCodEquip() != null
						&& castOther.getCodEquip() != null && this.getCodEquip().equals(castOther.getCodEquip())))
				&& ((this.getCodVar() == castOther.getCodVar()) || (this.getCodVar() != null
						&& castOther.getCodVar() != null && this.getCodVar().equals(castOther.getCodVar())))
				&& ((this.getCodFarm() == castOther.getCodFarm()) || (this.getCodFarm() != null
						&& castOther.getCodFarm() != null && this.getCodFarm().equals(castOther.getCodFarm())))
				&& ((this.getNomFarm() == castOther.getNomFarm()) || (this.getNomFarm() != null
						&& castOther.getNomFarm() != null && this.getNomFarm().equals(castOther.getNomFarm())))
				&& ((this.getCodParcel() == castOther.getCodParcel()) || (this.getCodParcel() != null
						&& castOther.getCodParcel() != null && this.getCodParcel().equals(castOther.getCodParcel())))
				&& ((this.getCodVil() == castOther.getCodVil()) || (this.getCodVil() != null
						&& castOther.getCodVil() != null && this.getCodVil().equals(castOther.getCodVil())))
				&& ((this.getLibVil() == castOther.getLibVil()) || (this.getLibVil() != null
						&& castOther.getLibVil() != null && this.getLibVil().equals(castOther.getLibVil())))
				&& ((this.getLibVar() == castOther.getLibVar()) || (this.getLibVar() != null
						&& castOther.getLibVar() != null && this.getLibVar().equals(castOther.getLibVar())))
				&& ((this.getPuFarm() == castOther.getPuFarm()) || (this.getPuFarm() != null
						&& castOther.getPuFarm() != null && this.getPuFarm().equals(castOther.getPuFarm())))
				&& ((this.getPuFou() == castOther.getPuFou()) || (this.getPuFou() != null
						&& castOther.getPuFou() != null && this.getPuFou().equals(castOther.getPuFou())))
				&& ((this.getMontfarm() == castOther.getMontfarm()) || (this.getMontfarm() != null
						&& castOther.getMontfarm() != null && this.getMontfarm().equals(castOther.getMontfarm())))
				&& ((this.getRefbe() == castOther.getRefbe()) || (this.getRefbe() != null
						&& castOther.getRefbe() != null && this.getRefbe().equals(castOther.getRefbe())))
				&& ((this.getDatcond() == castOther.getDatcond()) || (this.getDatcond() != null
						&& castOther.getDatcond() != null && this.getDatcond().equals(castOther.getDatcond())))
				&& ((this.getCodCal1() == castOther.getCodCal1()) || (this.getCodCal1() != null
						&& castOther.getCodCal1() != null && this.getCodCal1().equals(castOther.getCodCal1())))
				&& ((this.getQteCal1() == castOther.getQteCal1()) || (this.getQteCal1() != null
						&& castOther.getQteCal1() != null && this.getQteCal1().equals(castOther.getQteCal1())))
				&& ((this.getCodCal2() == castOther.getCodCal2()) || (this.getCodCal2() != null
						&& castOther.getCodCal2() != null && this.getCodCal2().equals(castOther.getCodCal2())))
				&& ((this.getQteCal2() == castOther.getQteCal2()) || (this.getQteCal2() != null
						&& castOther.getQteCal2() != null && this.getQteCal2().equals(castOther.getQteCal2())))
				&& ((this.getCodCal3() == castOther.getCodCal3()) || (this.getCodCal3() != null
						&& castOther.getCodCal3() != null && this.getCodCal3().equals(castOther.getCodCal3())))
				&& ((this.getQteCal3() == castOther.getQteCal3()) || (this.getQteCal3() != null
						&& castOther.getQteCal3() != null && this.getQteCal3().equals(castOther.getQteCal3())))
				&& ((this.getCodCal4() == castOther.getCodCal4()) || (this.getCodCal4() != null
						&& castOther.getCodCal4() != null && this.getCodCal4().equals(castOther.getCodCal4())))
				&& ((this.getQteCal4() == castOther.getQteCal4()) || (this.getQteCal4() != null
						&& castOther.getQteCal4() != null && this.getQteCal4().equals(castOther.getQteCal4())))
				&& ((this.getCodCal5() == castOther.getCodCal5()) || (this.getCodCal5() != null
						&& castOther.getCodCal5() != null && this.getCodCal5().equals(castOther.getCodCal5())))
				&& ((this.getQteCal5() == castOther.getQteCal5()) || (this.getQteCal5() != null
						&& castOther.getQteCal5() != null && this.getQteCal5().equals(castOther.getQteCal5())))
				&& ((this.getCodCal6() == castOther.getCodCal6()) || (this.getCodCal6() != null
						&& castOther.getCodCal6() != null && this.getCodCal6().equals(castOther.getCodCal6())))
				&& ((this.getQteCal6() == castOther.getQteCal6()) || (this.getQteCal6() != null
						&& castOther.getQteCal6() != null && this.getQteCal6().equals(castOther.getQteCal6())))
				&& ((this.getCodCal7() == castOther.getCodCal7()) || (this.getCodCal7() != null
						&& castOther.getCodCal7() != null && this.getCodCal7().equals(castOther.getCodCal7())))
				&& ((this.getQteCal7() == castOther.getQteCal7()) || (this.getQteCal7() != null
						&& castOther.getQteCal7() != null && this.getQteCal7().equals(castOther.getQteCal7())))
				&& ((this.getCodCal8() == castOther.getCodCal8()) || (this.getCodCal8() != null
						&& castOther.getCodCal8() != null && this.getCodCal8().equals(castOther.getCodCal8())))
				&& ((this.getQteCal8() == castOther.getQteCal8()) || (this.getQteCal8() != null
						&& castOther.getQteCal8() != null && this.getQteCal8().equals(castOther.getQteCal8())))
				&& ((this.getCodCal9() == castOther.getCodCal9()) || (this.getCodCal9() != null
						&& castOther.getCodCal9() != null && this.getCodCal9().equals(castOther.getCodCal9())))
				&& ((this.getQteCal9() == castOther.getQteCal9()) || (this.getQteCal9() != null
						&& castOther.getQteCal9() != null && this.getQteCal9().equals(castOther.getQteCal9())))
				&& ((this.getCodCal10() == castOther.getCodCal10()) || (this.getCodCal10() != null
						&& castOther.getCodCal10() != null && this.getCodCal10().equals(castOther.getCodCal10())))
				&& ((this.getQteCal10() == castOther.getQteCal10()) || (this.getQteCal10() != null
						&& castOther.getQteCal10() != null && this.getQteCal10().equals(castOther.getQteCal10())))
				&& ((this.getCodCal11() == castOther.getCodCal11()) || (this.getCodCal11() != null
						&& castOther.getCodCal11() != null && this.getCodCal11().equals(castOther.getCodCal11())))
				&& ((this.getQteCal11() == castOther.getQteCal11()) || (this.getQteCal11() != null
						&& castOther.getQteCal11() != null && this.getQteCal11().equals(castOther.getQteCal11())))
				&& ((this.getCodCal12() == castOther.getCodCal12()) || (this.getCodCal12() != null
						&& castOther.getCodCal12() != null && this.getCodCal12().equals(castOther.getCodCal12())))
				&& ((this.getQteCal12() == castOther.getQteCal12()) || (this.getQteCal12() != null
						&& castOther.getQteCal12() != null && this.getQteCal12().equals(castOther.getQteCal12())))
				&& ((this.getQteTore() == castOther.getQteTore()) || (this.getQteTore() != null
						&& castOther.getQteTore() != null && this.getQteTore().equals(castOther.getQteTore())))
				&& ((this.getQteNtore() == castOther.getQteNtore()) || (this.getQteNtore() != null
						&& castOther.getQteNtore() != null && this.getQteNtore().equals(castOther.getQteNtore())))
				&& ((this.getQteSpoid() == castOther.getQteSpoid()) || (this.getQteSpoid() != null
						&& castOther.getQteSpoid() != null && this.getQteSpoid().equals(castOther.getQteSpoid())))
				&& ((this.getQteTot() == castOther.getQteTot()) || (this.getQteTot() != null
						&& castOther.getQteTot() != null && this.getQteTot().equals(castOther.getQteTot())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNobe() == null ? 0 : this.getNobe().hashCode());
		result = 37 * result + (getDatbe() == null ? 0 : this.getDatbe().hashCode());
		result = 37 * result + (getRaisonFou() == null ? 0 : this.getRaisonFou().hashCode());
		result = 37 * result + (getPoidnet() == null ? 0 : this.getPoidnet().hashCode());
		result = 37 * result + (getConnais() == null ? 0 : this.getConnais().hashCode());
		result = 37 * result + (getCodFou() == null ? 0 : this.getCodFou().hashCode());
		result = 37 * result + (getCodUom() == null ? 0 : this.getCodUom().hashCode());
		result = 37 * result + (getTareSac() == null ? 0 : this.getTareSac().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getCamion() == null ? 0 : this.getCamion().hashCode());
		result = 37 * result + (getRemorq() == null ? 0 : this.getRemorq().hashCode());
		result = 37 * result + (getPoiddec() == null ? 0 : this.getPoiddec().hashCode());
		result = 37 * result + (getEcartPoid() == null ? 0 : this.getEcartPoid().hashCode());
		result = 37 * result + (getCodMag() == null ? 0 : this.getCodMag().hashCode());
		result = 37 * result + (getCodStat() == null ? 0 : this.getCodStat().hashCode());
		result = 37 * result + (getMatPers() == null ? 0 : this.getMatPers().hashCode());
		result = 37 * result + (getChauffeur() == null ? 0 : this.getChauffeur().hashCode());
		result = 37 * result + (getDecision() == null ? 0 : this.getDecision().hashCode());
		result = 37 * result + (getDateAdd() == null ? 0 : this.getDateAdd().hashCode());
		result = 37 * result + (getDateEdit() == null ? 0 : this.getDateEdit().hashCode());
		result = 37 * result + (getCodUtVal() == null ? 0 : this.getCodUtVal().hashCode());
		result = 37 * result + (getDateValid() == null ? 0 : this.getDateValid().hashCode());
		result = 37 * result + (getTimeValid() == null ? 0 : this.getTimeValid().hashCode());
		result = 37 * result + (getCodTrans() == null ? 0 : this.getCodTrans().hashCode());
		result = 37 * result + (getNoCont() == null ? 0 : this.getNoCont().hashCode());
		result = 37 * result + (getQte1() == null ? 0 : this.getQte1().hashCode());
		result = 37 * result + (getQte2() == null ? 0 : this.getQte2().hashCode());
		result = 37 * result + (getQte3() == null ? 0 : this.getQte3().hashCode());
		result = 37 * result + (getQtet() == null ? 0 : this.getQtet().hashCode());
		result = 37 * result + (getMt1() == null ? 0 : this.getMt1().hashCode());
		result = 37 * result + (getMt2() == null ? 0 : this.getMt2().hashCode());
		result = 37 * result + (getMt3() == null ? 0 : this.getMt3().hashCode());
		result = 37 * result + (getMontant() == null ? 0 : this.getMontant().hashCode());
		result = 37 * result + (getDatdeb() == null ? 0 : this.getDatdeb().hashCode());
		result = 37 * result + (getDatfin() == null ? 0 : this.getDatfin().hashCode());
		result = 37 * result + (getCodQ1() == null ? 0 : this.getCodQ1().hashCode());
		result = 37 * result + (getCodQ2() == null ? 0 : this.getCodQ2().hashCode());
		result = 37 * result + (getLibQ1() == null ? 0 : this.getLibQ1().hashCode());
		result = 37 * result + (getLibQ2() == null ? 0 : this.getLibQ2().hashCode());
		result = 37 * result + (getCodEquip() == null ? 0 : this.getCodEquip().hashCode());
		result = 37 * result + (getCodVar() == null ? 0 : this.getCodVar().hashCode());
		result = 37 * result + (getCodFarm() == null ? 0 : this.getCodFarm().hashCode());
		result = 37 * result + (getNomFarm() == null ? 0 : this.getNomFarm().hashCode());
		result = 37 * result + (getCodParcel() == null ? 0 : this.getCodParcel().hashCode());
		result = 37 * result + (getCodVil() == null ? 0 : this.getCodVil().hashCode());
		result = 37 * result + (getLibVil() == null ? 0 : this.getLibVil().hashCode());
		result = 37 * result + (getLibVar() == null ? 0 : this.getLibVar().hashCode());
		result = 37 * result + (getPuFarm() == null ? 0 : this.getPuFarm().hashCode());
		result = 37 * result + (getPuFou() == null ? 0 : this.getPuFou().hashCode());
		result = 37 * result + (getMontfarm() == null ? 0 : this.getMontfarm().hashCode());
		result = 37 * result + (getRefbe() == null ? 0 : this.getRefbe().hashCode());
		result = 37 * result + (getDatcond() == null ? 0 : this.getDatcond().hashCode());
		result = 37 * result + (getCodCal1() == null ? 0 : this.getCodCal1().hashCode());
		result = 37 * result + (getQteCal1() == null ? 0 : this.getQteCal1().hashCode());
		result = 37 * result + (getCodCal2() == null ? 0 : this.getCodCal2().hashCode());
		result = 37 * result + (getQteCal2() == null ? 0 : this.getQteCal2().hashCode());
		result = 37 * result + (getCodCal3() == null ? 0 : this.getCodCal3().hashCode());
		result = 37 * result + (getQteCal3() == null ? 0 : this.getQteCal3().hashCode());
		result = 37 * result + (getCodCal4() == null ? 0 : this.getCodCal4().hashCode());
		result = 37 * result + (getQteCal4() == null ? 0 : this.getQteCal4().hashCode());
		result = 37 * result + (getCodCal5() == null ? 0 : this.getCodCal5().hashCode());
		result = 37 * result + (getQteCal5() == null ? 0 : this.getQteCal5().hashCode());
		result = 37 * result + (getCodCal6() == null ? 0 : this.getCodCal6().hashCode());
		result = 37 * result + (getQteCal6() == null ? 0 : this.getQteCal6().hashCode());
		result = 37 * result + (getCodCal7() == null ? 0 : this.getCodCal7().hashCode());
		result = 37 * result + (getQteCal7() == null ? 0 : this.getQteCal7().hashCode());
		result = 37 * result + (getCodCal8() == null ? 0 : this.getCodCal8().hashCode());
		result = 37 * result + (getQteCal8() == null ? 0 : this.getQteCal8().hashCode());
		result = 37 * result + (getCodCal9() == null ? 0 : this.getCodCal9().hashCode());
		result = 37 * result + (getQteCal9() == null ? 0 : this.getQteCal9().hashCode());
		result = 37 * result + (getCodCal10() == null ? 0 : this.getCodCal10().hashCode());
		result = 37 * result + (getQteCal10() == null ? 0 : this.getQteCal10().hashCode());
		result = 37 * result + (getCodCal11() == null ? 0 : this.getCodCal11().hashCode());
		result = 37 * result + (getQteCal11() == null ? 0 : this.getQteCal11().hashCode());
		result = 37 * result + (getCodCal12() == null ? 0 : this.getCodCal12().hashCode());
		result = 37 * result + (getQteCal12() == null ? 0 : this.getQteCal12().hashCode());
		result = 37 * result + (getQteTore() == null ? 0 : this.getQteTore().hashCode());
		result = 37 * result + (getQteNtore() == null ? 0 : this.getQteNtore().hashCode());
		result = 37 * result + (getQteSpoid() == null ? 0 : this.getQteSpoid().hashCode());
		result = 37 * result + (getQteTot() == null ? 0 : this.getQteTot().hashCode());
		return result;
	}

}
