package com.gts.expersoft.models;
// Generated Mar 9, 2018 3:36:12 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * CalibreId generated by hbm2java
 */
public class Calibre implements java.io.Serializable {

	private String codCali;
	private String libProd;
	private String libCali;
	private String codProd;
	private Integer ordre;
	private String abrege;
	private Double bornInf;
	private Double bornSup;
	private Double tareEmb;
	private Double poidEmb;

	public Calibre() {
	}

	public Calibre(String codCali, String libProd, String libCali, String codProd, Integer ordre, String abrege,
			Double bornInf, Double bornSup, Double tareEmb, Double poidEmb) {
		this.codCali = codCali;
		this.libProd = libProd;
		this.libCali = libCali;
		this.codProd = codProd;
		this.ordre = ordre;
		this.abrege = abrege;
		this.bornInf = bornInf;
		this.bornSup = bornSup;
		this.tareEmb = tareEmb;
		this.poidEmb = poidEmb;
	}

	public String getCodCali() {
		return this.codCali;
	}

	public void setCodCali(String codCali) {
		this.codCali = codCali;
	}

	public String getLibProd() {
		return this.libProd;
	}

	public void setLibProd(String libProd) {
		this.libProd = libProd;
	}

	public String getLibCali() {
		return this.libCali;
	}

	public void setLibCali(String libCali) {
		this.libCali = libCali;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	public String getAbrege() {
		return this.abrege;
	}

	public void setAbrege(String abrege) {
		this.abrege = abrege;
	}

	public Double getBornInf() {
		return this.bornInf;
	}

	public void setBornInf(Double bornInf) {
		this.bornInf = bornInf;
	}

	public Double getBornSup() {
		return this.bornSup;
	}

	public void setBornSup(Double bornSup) {
		this.bornSup = bornSup;
	}

	public Double getTareEmb() {
		return this.tareEmb;
	}

	public void setTareEmb(Double tareEmb) {
		this.tareEmb = tareEmb;
	}

	public Double getPoidEmb() {
		return this.poidEmb;
	}

	public void setPoidEmb(Double poidEmb) {
		this.poidEmb = poidEmb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Calibre))
			return false;
		Calibre castOther = (Calibre) other;

		return ((this.getCodCali() == castOther.getCodCali()) || (this.getCodCali() != null
				&& castOther.getCodCali() != null && this.getCodCali().equals(castOther.getCodCali())))
				&& ((this.getLibProd() == castOther.getLibProd()) || (this.getLibProd() != null
						&& castOther.getLibProd() != null && this.getLibProd().equals(castOther.getLibProd())))
				&& ((this.getLibCali() == castOther.getLibCali()) || (this.getLibCali() != null
						&& castOther.getLibCali() != null && this.getLibCali().equals(castOther.getLibCali())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getOrdre() == castOther.getOrdre()) || (this.getOrdre() != null
						&& castOther.getOrdre() != null && this.getOrdre().equals(castOther.getOrdre())))
				&& ((this.getAbrege() == castOther.getAbrege()) || (this.getAbrege() != null
						&& castOther.getAbrege() != null && this.getAbrege().equals(castOther.getAbrege())))
				&& ((this.getBornInf() == castOther.getBornInf()) || (this.getBornInf() != null
						&& castOther.getBornInf() != null && this.getBornInf().equals(castOther.getBornInf())))
				&& ((this.getBornSup() == castOther.getBornSup()) || (this.getBornSup() != null
						&& castOther.getBornSup() != null && this.getBornSup().equals(castOther.getBornSup())))
				&& ((this.getTareEmb() == castOther.getTareEmb()) || (this.getTareEmb() != null
						&& castOther.getTareEmb() != null && this.getTareEmb().equals(castOther.getTareEmb())))
				&& ((this.getPoidEmb() == castOther.getPoidEmb()) || (this.getPoidEmb() != null
						&& castOther.getPoidEmb() != null && this.getPoidEmb().equals(castOther.getPoidEmb())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodCali() == null ? 0 : this.getCodCali().hashCode());
		result = 37 * result + (getLibProd() == null ? 0 : this.getLibProd().hashCode());
		result = 37 * result + (getLibCali() == null ? 0 : this.getLibCali().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getOrdre() == null ? 0 : this.getOrdre().hashCode());
		result = 37 * result + (getAbrege() == null ? 0 : this.getAbrege().hashCode());
		result = 37 * result + (getBornInf() == null ? 0 : this.getBornInf().hashCode());
		result = 37 * result + (getBornSup() == null ? 0 : this.getBornSup().hashCode());
		result = 37 * result + (getTareEmb() == null ? 0 : this.getTareEmb().hashCode());
		result = 37 * result + (getPoidEmb() == null ? 0 : this.getPoidEmb().hashCode());
		return result;
	}

}
