package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private ClientId id;

	public Client() {
	}

	public Client(ClientId id) {
		this.id = id;
	}

	public ClientId getId() {
		return this.id;
	}

	public void setId(ClientId id) {
		this.id = id;
	}

}
