package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ContfId generated by hbm2java
 */
public class ContfId implements java.io.Serializable {

	private String nom;
	private String contact;
	private String fonction;
	private String refPiece;
	private String codFou;
	private String num;
	private String ins;

	public ContfId() {
	}

	public ContfId(String nom, String contact, String fonction, String refPiece, String codFou, String num,
			String ins) {
		this.nom = nom;
		this.contact = contact;
		this.fonction = fonction;
		this.refPiece = refPiece;
		this.codFou = codFou;
		this.num = num;
		this.ins = ins;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public String getRefPiece() {
		return this.refPiece;
	}

	public void setRefPiece(String refPiece) {
		this.refPiece = refPiece;
	}

	public String getCodFou() {
		return this.codFou;
	}

	public void setCodFou(String codFou) {
		this.codFou = codFou;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getIns() {
		return this.ins;
	}

	public void setIns(String ins) {
		this.ins = ins;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContfId))
			return false;
		ContfId castOther = (ContfId) other;

		return ((this.getNom() == castOther.getNom())
				|| (this.getNom() != null && castOther.getNom() != null && this.getNom().equals(castOther.getNom())))
				&& ((this.getContact() == castOther.getContact()) || (this.getContact() != null
						&& castOther.getContact() != null && this.getContact().equals(castOther.getContact())))
				&& ((this.getFonction() == castOther.getFonction()) || (this.getFonction() != null
						&& castOther.getFonction() != null && this.getFonction().equals(castOther.getFonction())))
				&& ((this.getRefPiece() == castOther.getRefPiece()) || (this.getRefPiece() != null
						&& castOther.getRefPiece() != null && this.getRefPiece().equals(castOther.getRefPiece())))
				&& ((this.getCodFou() == castOther.getCodFou()) || (this.getCodFou() != null
						&& castOther.getCodFou() != null && this.getCodFou().equals(castOther.getCodFou())))
				&& ((this.getNum() == castOther.getNum()) || (this.getNum() != null && castOther.getNum() != null
						&& this.getNum().equals(castOther.getNum())))
				&& ((this.getIns() == castOther.getIns()) || (this.getIns() != null && castOther.getIns() != null
						&& this.getIns().equals(castOther.getIns())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNom() == null ? 0 : this.getNom().hashCode());
		result = 37 * result + (getContact() == null ? 0 : this.getContact().hashCode());
		result = 37 * result + (getFonction() == null ? 0 : this.getFonction().hashCode());
		result = 37 * result + (getRefPiece() == null ? 0 : this.getRefPiece().hashCode());
		result = 37 * result + (getCodFou() == null ? 0 : this.getCodFou().hashCode());
		result = 37 * result + (getNum() == null ? 0 : this.getNum().hashCode());
		result = 37 * result + (getIns() == null ? 0 : this.getIns().hashCode());
		return result;
	}

}
