package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ContratfId generated by hbm2java
 */
public class ContratfId implements java.io.Serializable {

	private String noCont;
	private String datcont;
	private String raisonFou;
	private String refCont;
	private String codFou;
	private String codProd;
	private Double qteCont;
	private Double puCont;
	private Double mtCont;
	private Double qteLivre;
	private Double qteRest;
	private Double montLivre;
	private String datdeb;
	private String datfin;
	private String codUom;

	public ContratfId() {
	}

	public ContratfId(String noCont, String datcont, String raisonFou, String refCont, String codFou, String codProd,
			Double qteCont, Double puCont, Double mtCont, Double qteLivre, Double qteRest, Double montLivre,
			String datdeb, String datfin, String codUom) {
		this.noCont = noCont;
		this.datcont = datcont;
		this.raisonFou = raisonFou;
		this.refCont = refCont;
		this.codFou = codFou;
		this.codProd = codProd;
		this.qteCont = qteCont;
		this.puCont = puCont;
		this.mtCont = mtCont;
		this.qteLivre = qteLivre;
		this.qteRest = qteRest;
		this.montLivre = montLivre;
		this.datdeb = datdeb;
		this.datfin = datfin;
		this.codUom = codUom;
	}

	public String getNoCont() {
		return this.noCont;
	}

	public void setNoCont(String noCont) {
		this.noCont = noCont;
	}

	public String getDatcont() {
		return this.datcont;
	}

	public void setDatcont(String datcont) {
		this.datcont = datcont;
	}

	public String getRaisonFou() {
		return this.raisonFou;
	}

	public void setRaisonFou(String raisonFou) {
		this.raisonFou = raisonFou;
	}

	public String getRefCont() {
		return this.refCont;
	}

	public void setRefCont(String refCont) {
		this.refCont = refCont;
	}

	public String getCodFou() {
		return this.codFou;
	}

	public void setCodFou(String codFou) {
		this.codFou = codFou;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public Double getQteCont() {
		return this.qteCont;
	}

	public void setQteCont(Double qteCont) {
		this.qteCont = qteCont;
	}

	public Double getPuCont() {
		return this.puCont;
	}

	public void setPuCont(Double puCont) {
		this.puCont = puCont;
	}

	public Double getMtCont() {
		return this.mtCont;
	}

	public void setMtCont(Double mtCont) {
		this.mtCont = mtCont;
	}

	public Double getQteLivre() {
		return this.qteLivre;
	}

	public void setQteLivre(Double qteLivre) {
		this.qteLivre = qteLivre;
	}

	public Double getQteRest() {
		return this.qteRest;
	}

	public void setQteRest(Double qteRest) {
		this.qteRest = qteRest;
	}

	public Double getMontLivre() {
		return this.montLivre;
	}

	public void setMontLivre(Double montLivre) {
		this.montLivre = montLivre;
	}

	public String getDatdeb() {
		return this.datdeb;
	}

	public void setDatdeb(String datdeb) {
		this.datdeb = datdeb;
	}

	public String getDatfin() {
		return this.datfin;
	}

	public void setDatfin(String datfin) {
		this.datfin = datfin;
	}

	public String getCodUom() {
		return this.codUom;
	}

	public void setCodUom(String codUom) {
		this.codUom = codUom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContratfId))
			return false;
		ContratfId castOther = (ContratfId) other;

		return ((this.getNoCont() == castOther.getNoCont()) || (this.getNoCont() != null
				&& castOther.getNoCont() != null && this.getNoCont().equals(castOther.getNoCont())))
				&& ((this.getDatcont() == castOther.getDatcont()) || (this.getDatcont() != null
						&& castOther.getDatcont() != null && this.getDatcont().equals(castOther.getDatcont())))
				&& ((this.getRaisonFou() == castOther.getRaisonFou()) || (this.getRaisonFou() != null
						&& castOther.getRaisonFou() != null && this.getRaisonFou().equals(castOther.getRaisonFou())))
				&& ((this.getRefCont() == castOther.getRefCont()) || (this.getRefCont() != null
						&& castOther.getRefCont() != null && this.getRefCont().equals(castOther.getRefCont())))
				&& ((this.getCodFou() == castOther.getCodFou()) || (this.getCodFou() != null
						&& castOther.getCodFou() != null && this.getCodFou().equals(castOther.getCodFou())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getQteCont() == castOther.getQteCont()) || (this.getQteCont() != null
						&& castOther.getQteCont() != null && this.getQteCont().equals(castOther.getQteCont())))
				&& ((this.getPuCont() == castOther.getPuCont()) || (this.getPuCont() != null
						&& castOther.getPuCont() != null && this.getPuCont().equals(castOther.getPuCont())))
				&& ((this.getMtCont() == castOther.getMtCont()) || (this.getMtCont() != null
						&& castOther.getMtCont() != null && this.getMtCont().equals(castOther.getMtCont())))
				&& ((this.getQteLivre() == castOther.getQteLivre()) || (this.getQteLivre() != null
						&& castOther.getQteLivre() != null && this.getQteLivre().equals(castOther.getQteLivre())))
				&& ((this.getQteRest() == castOther.getQteRest()) || (this.getQteRest() != null
						&& castOther.getQteRest() != null && this.getQteRest().equals(castOther.getQteRest())))
				&& ((this.getMontLivre() == castOther.getMontLivre()) || (this.getMontLivre() != null
						&& castOther.getMontLivre() != null && this.getMontLivre().equals(castOther.getMontLivre())))
				&& ((this.getDatdeb() == castOther.getDatdeb()) || (this.getDatdeb() != null
						&& castOther.getDatdeb() != null && this.getDatdeb().equals(castOther.getDatdeb())))
				&& ((this.getDatfin() == castOther.getDatfin()) || (this.getDatfin() != null
						&& castOther.getDatfin() != null && this.getDatfin().equals(castOther.getDatfin())))
				&& ((this.getCodUom() == castOther.getCodUom()) || (this.getCodUom() != null
						&& castOther.getCodUom() != null && this.getCodUom().equals(castOther.getCodUom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNoCont() == null ? 0 : this.getNoCont().hashCode());
		result = 37 * result + (getDatcont() == null ? 0 : this.getDatcont().hashCode());
		result = 37 * result + (getRaisonFou() == null ? 0 : this.getRaisonFou().hashCode());
		result = 37 * result + (getRefCont() == null ? 0 : this.getRefCont().hashCode());
		result = 37 * result + (getCodFou() == null ? 0 : this.getCodFou().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getQteCont() == null ? 0 : this.getQteCont().hashCode());
		result = 37 * result + (getPuCont() == null ? 0 : this.getPuCont().hashCode());
		result = 37 * result + (getMtCont() == null ? 0 : this.getMtCont().hashCode());
		result = 37 * result + (getQteLivre() == null ? 0 : this.getQteLivre().hashCode());
		result = 37 * result + (getQteRest() == null ? 0 : this.getQteRest().hashCode());
		result = 37 * result + (getMontLivre() == null ? 0 : this.getMontLivre().hashCode());
		result = 37 * result + (getDatdeb() == null ? 0 : this.getDatdeb().hashCode());
		result = 37 * result + (getDatfin() == null ? 0 : this.getDatfin().hashCode());
		result = 37 * result + (getCodUom() == null ? 0 : this.getCodUom().hashCode());
		return result;
	}

}
