package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Contratf generated by hbm2java
 */
public class Contratf implements java.io.Serializable {

	private ContratfId id;

	public Contratf() {
	}

	public Contratf(ContratfId id) {
		this.id = id;
	}

	public ContratfId getId() {
		return this.id;
	}

	public void setId(ContratfId id) {
		this.id = id;
	}

}
