package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Contratc generated by hbm2java
 */
public class Contratc implements java.io.Serializable {

	private ContratcId id;

	public Contratc() {
	}

	public Contratc(ContratcId id) {
		this.id = id;
	}

	public ContratcId getId() {
		return this.id;
	}

	public void setId(ContratcId id) {
		this.id = id;
	}

}
