package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ContratcId generated by hbm2java
 */
public class ContratcId implements java.io.Serializable {

	private String noCont;
	private String datcont;
	private String raisonCli;
	private String refCont;
	private String codCli;
	private String codProd;
	private Double qteCont;
	private Double puCont;
	private Double mtCont;
	private Double qteLivre;
	private Double qteRest;
	private String datdeb;
	private String datfin;
	private String codUom;

	public ContratcId() {
	}

	public ContratcId(String noCont, String datcont, String raisonCli, String refCont, String codCli, String codProd,
			Double qteCont, Double puCont, Double mtCont, Double qteLivre, Double qteRest, String datdeb, String datfin,
			String codUom) {
		this.noCont = noCont;
		this.datcont = datcont;
		this.raisonCli = raisonCli;
		this.refCont = refCont;
		this.codCli = codCli;
		this.codProd = codProd;
		this.qteCont = qteCont;
		this.puCont = puCont;
		this.mtCont = mtCont;
		this.qteLivre = qteLivre;
		this.qteRest = qteRest;
		this.datdeb = datdeb;
		this.datfin = datfin;
		this.codUom = codUom;
	}

	public String getNoCont() {
		return this.noCont;
	}

	public void setNoCont(String noCont) {
		this.noCont = noCont;
	}

	public String getDatcont() {
		return this.datcont;
	}

	public void setDatcont(String datcont) {
		this.datcont = datcont;
	}

	public String getRaisonCli() {
		return this.raisonCli;
	}

	public void setRaisonCli(String raisonCli) {
		this.raisonCli = raisonCli;
	}

	public String getRefCont() {
		return this.refCont;
	}

	public void setRefCont(String refCont) {
		this.refCont = refCont;
	}

	public String getCodCli() {
		return this.codCli;
	}

	public void setCodCli(String codCli) {
		this.codCli = codCli;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public Double getQteCont() {
		return this.qteCont;
	}

	public void setQteCont(Double qteCont) {
		this.qteCont = qteCont;
	}

	public Double getPuCont() {
		return this.puCont;
	}

	public void setPuCont(Double puCont) {
		this.puCont = puCont;
	}

	public Double getMtCont() {
		return this.mtCont;
	}

	public void setMtCont(Double mtCont) {
		this.mtCont = mtCont;
	}

	public Double getQteLivre() {
		return this.qteLivre;
	}

	public void setQteLivre(Double qteLivre) {
		this.qteLivre = qteLivre;
	}

	public Double getQteRest() {
		return this.qteRest;
	}

	public void setQteRest(Double qteRest) {
		this.qteRest = qteRest;
	}

	public String getDatdeb() {
		return this.datdeb;
	}

	public void setDatdeb(String datdeb) {
		this.datdeb = datdeb;
	}

	public String getDatfin() {
		return this.datfin;
	}

	public void setDatfin(String datfin) {
		this.datfin = datfin;
	}

	public String getCodUom() {
		return this.codUom;
	}

	public void setCodUom(String codUom) {
		this.codUom = codUom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContratcId))
			return false;
		ContratcId castOther = (ContratcId) other;

		return ((this.getNoCont() == castOther.getNoCont()) || (this.getNoCont() != null
				&& castOther.getNoCont() != null && this.getNoCont().equals(castOther.getNoCont())))
				&& ((this.getDatcont() == castOther.getDatcont()) || (this.getDatcont() != null
						&& castOther.getDatcont() != null && this.getDatcont().equals(castOther.getDatcont())))
				&& ((this.getRaisonCli() == castOther.getRaisonCli()) || (this.getRaisonCli() != null
						&& castOther.getRaisonCli() != null && this.getRaisonCli().equals(castOther.getRaisonCli())))
				&& ((this.getRefCont() == castOther.getRefCont()) || (this.getRefCont() != null
						&& castOther.getRefCont() != null && this.getRefCont().equals(castOther.getRefCont())))
				&& ((this.getCodCli() == castOther.getCodCli()) || (this.getCodCli() != null
						&& castOther.getCodCli() != null && this.getCodCli().equals(castOther.getCodCli())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getQteCont() == castOther.getQteCont()) || (this.getQteCont() != null
						&& castOther.getQteCont() != null && this.getQteCont().equals(castOther.getQteCont())))
				&& ((this.getPuCont() == castOther.getPuCont()) || (this.getPuCont() != null
						&& castOther.getPuCont() != null && this.getPuCont().equals(castOther.getPuCont())))
				&& ((this.getMtCont() == castOther.getMtCont()) || (this.getMtCont() != null
						&& castOther.getMtCont() != null && this.getMtCont().equals(castOther.getMtCont())))
				&& ((this.getQteLivre() == castOther.getQteLivre()) || (this.getQteLivre() != null
						&& castOther.getQteLivre() != null && this.getQteLivre().equals(castOther.getQteLivre())))
				&& ((this.getQteRest() == castOther.getQteRest()) || (this.getQteRest() != null
						&& castOther.getQteRest() != null && this.getQteRest().equals(castOther.getQteRest())))
				&& ((this.getDatdeb() == castOther.getDatdeb()) || (this.getDatdeb() != null
						&& castOther.getDatdeb() != null && this.getDatdeb().equals(castOther.getDatdeb())))
				&& ((this.getDatfin() == castOther.getDatfin()) || (this.getDatfin() != null
						&& castOther.getDatfin() != null && this.getDatfin().equals(castOther.getDatfin())))
				&& ((this.getCodUom() == castOther.getCodUom()) || (this.getCodUom() != null
						&& castOther.getCodUom() != null && this.getCodUom().equals(castOther.getCodUom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNoCont() == null ? 0 : this.getNoCont().hashCode());
		result = 37 * result + (getDatcont() == null ? 0 : this.getDatcont().hashCode());
		result = 37 * result + (getRaisonCli() == null ? 0 : this.getRaisonCli().hashCode());
		result = 37 * result + (getRefCont() == null ? 0 : this.getRefCont().hashCode());
		result = 37 * result + (getCodCli() == null ? 0 : this.getCodCli().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getQteCont() == null ? 0 : this.getQteCont().hashCode());
		result = 37 * result + (getPuCont() == null ? 0 : this.getPuCont().hashCode());
		result = 37 * result + (getMtCont() == null ? 0 : this.getMtCont().hashCode());
		result = 37 * result + (getQteLivre() == null ? 0 : this.getQteLivre().hashCode());
		result = 37 * result + (getQteRest() == null ? 0 : this.getQteRest().hashCode());
		result = 37 * result + (getDatdeb() == null ? 0 : this.getDatdeb().hashCode());
		result = 37 * result + (getDatfin() == null ? 0 : this.getDatfin().hashCode());
		result = 37 * result + (getCodUom() == null ? 0 : this.getCodUom().hashCode());
		return result;
	}

}
