package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Contf generated by hbm2java
 */
public class Contf implements java.io.Serializable {

	private ContfId id;

	public Contf() {
	}

	public Contf(ContfId id) {
		this.id = id;
	}

	public ContfId getId() {
		return this.id;
	}

	public void setId(ContfId id) {
		this.id = id;
	}

}
