package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * DetfinId generated by hbm2java
 */
public class DetfinId implements java.io.Serializable {

	private String codDetfin;
	private String libDetfin;
	private String unite;
	private Integer ordre;
	private Double qteHa;
	private Double qteSac;
	private Double puAch;
	private Double puVte;
	private Double coefConv;
	private String unitconv;
	private Double stockD;
	private String descrip;
	private String codTypfin;
	private Double stockM;
	private String libTypfin;

	public DetfinId() {
	}

	public DetfinId(String codDetfin, String libDetfin, String unite, Integer ordre, Double qteHa, Double qteSac,
			Double puAch, Double puVte, Double coefConv, String unitconv, Double stockD, String descrip,
			String codTypfin, Double stockM, String libTypfin) {
		this.codDetfin = codDetfin;
		this.libDetfin = libDetfin;
		this.unite = unite;
		this.ordre = ordre;
		this.qteHa = qteHa;
		this.qteSac = qteSac;
		this.puAch = puAch;
		this.puVte = puVte;
		this.coefConv = coefConv;
		this.unitconv = unitconv;
		this.stockD = stockD;
		this.descrip = descrip;
		this.codTypfin = codTypfin;
		this.stockM = stockM;
		this.libTypfin = libTypfin;
	}

	public String getCodDetfin() {
		return this.codDetfin;
	}

	public void setCodDetfin(String codDetfin) {
		this.codDetfin = codDetfin;
	}

	public String getLibDetfin() {
		return this.libDetfin;
	}

	public void setLibDetfin(String libDetfin) {
		this.libDetfin = libDetfin;
	}

	public String getUnite() {
		return this.unite;
	}

	public void setUnite(String unite) {
		this.unite = unite;
	}

	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	public Double getQteHa() {
		return this.qteHa;
	}

	public void setQteHa(Double qteHa) {
		this.qteHa = qteHa;
	}

	public Double getQteSac() {
		return this.qteSac;
	}

	public void setQteSac(Double qteSac) {
		this.qteSac = qteSac;
	}

	public Double getPuAch() {
		return this.puAch;
	}

	public void setPuAch(Double puAch) {
		this.puAch = puAch;
	}

	public Double getPuVte() {
		return this.puVte;
	}

	public void setPuVte(Double puVte) {
		this.puVte = puVte;
	}

	public Double getCoefConv() {
		return this.coefConv;
	}

	public void setCoefConv(Double coefConv) {
		this.coefConv = coefConv;
	}

	public String getUnitconv() {
		return this.unitconv;
	}

	public void setUnitconv(String unitconv) {
		this.unitconv = unitconv;
	}

	public Double getStockD() {
		return this.stockD;
	}

	public void setStockD(Double stockD) {
		this.stockD = stockD;
	}

	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public String getCodTypfin() {
		return this.codTypfin;
	}

	public void setCodTypfin(String codTypfin) {
		this.codTypfin = codTypfin;
	}

	public Double getStockM() {
		return this.stockM;
	}

	public void setStockM(Double stockM) {
		this.stockM = stockM;
	}

	public String getLibTypfin() {
		return this.libTypfin;
	}

	public void setLibTypfin(String libTypfin) {
		this.libTypfin = libTypfin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetfinId))
			return false;
		DetfinId castOther = (DetfinId) other;

		return ((this.getCodDetfin() == castOther.getCodDetfin()) || (this.getCodDetfin() != null
				&& castOther.getCodDetfin() != null && this.getCodDetfin().equals(castOther.getCodDetfin())))
				&& ((this.getLibDetfin() == castOther.getLibDetfin()) || (this.getLibDetfin() != null
						&& castOther.getLibDetfin() != null && this.getLibDetfin().equals(castOther.getLibDetfin())))
				&& ((this.getUnite() == castOther.getUnite()) || (this.getUnite() != null
						&& castOther.getUnite() != null && this.getUnite().equals(castOther.getUnite())))
				&& ((this.getOrdre() == castOther.getOrdre()) || (this.getOrdre() != null
						&& castOther.getOrdre() != null && this.getOrdre().equals(castOther.getOrdre())))
				&& ((this.getQteHa() == castOther.getQteHa()) || (this.getQteHa() != null
						&& castOther.getQteHa() != null && this.getQteHa().equals(castOther.getQteHa())))
				&& ((this.getQteSac() == castOther.getQteSac()) || (this.getQteSac() != null
						&& castOther.getQteSac() != null && this.getQteSac().equals(castOther.getQteSac())))
				&& ((this.getPuAch() == castOther.getPuAch()) || (this.getPuAch() != null
						&& castOther.getPuAch() != null && this.getPuAch().equals(castOther.getPuAch())))
				&& ((this.getPuVte() == castOther.getPuVte()) || (this.getPuVte() != null
						&& castOther.getPuVte() != null && this.getPuVte().equals(castOther.getPuVte())))
				&& ((this.getCoefConv() == castOther.getCoefConv()) || (this.getCoefConv() != null
						&& castOther.getCoefConv() != null && this.getCoefConv().equals(castOther.getCoefConv())))
				&& ((this.getUnitconv() == castOther.getUnitconv()) || (this.getUnitconv() != null
						&& castOther.getUnitconv() != null && this.getUnitconv().equals(castOther.getUnitconv())))
				&& ((this.getStockD() == castOther.getStockD()) || (this.getStockD() != null
						&& castOther.getStockD() != null && this.getStockD().equals(castOther.getStockD())))
				&& ((this.getDescrip() == castOther.getDescrip()) || (this.getDescrip() != null
						&& castOther.getDescrip() != null && this.getDescrip().equals(castOther.getDescrip())))
				&& ((this.getCodTypfin() == castOther.getCodTypfin()) || (this.getCodTypfin() != null
						&& castOther.getCodTypfin() != null && this.getCodTypfin().equals(castOther.getCodTypfin())))
				&& ((this.getStockM() == castOther.getStockM()) || (this.getStockM() != null
						&& castOther.getStockM() != null && this.getStockM().equals(castOther.getStockM())))
				&& ((this.getLibTypfin() == castOther.getLibTypfin()) || (this.getLibTypfin() != null
						&& castOther.getLibTypfin() != null && this.getLibTypfin().equals(castOther.getLibTypfin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodDetfin() == null ? 0 : this.getCodDetfin().hashCode());
		result = 37 * result + (getLibDetfin() == null ? 0 : this.getLibDetfin().hashCode());
		result = 37 * result + (getUnite() == null ? 0 : this.getUnite().hashCode());
		result = 37 * result + (getOrdre() == null ? 0 : this.getOrdre().hashCode());
		result = 37 * result + (getQteHa() == null ? 0 : this.getQteHa().hashCode());
		result = 37 * result + (getQteSac() == null ? 0 : this.getQteSac().hashCode());
		result = 37 * result + (getPuAch() == null ? 0 : this.getPuAch().hashCode());
		result = 37 * result + (getPuVte() == null ? 0 : this.getPuVte().hashCode());
		result = 37 * result + (getCoefConv() == null ? 0 : this.getCoefConv().hashCode());
		result = 37 * result + (getUnitconv() == null ? 0 : this.getUnitconv().hashCode());
		result = 37 * result + (getStockD() == null ? 0 : this.getStockD().hashCode());
		result = 37 * result + (getDescrip() == null ? 0 : this.getDescrip().hashCode());
		result = 37 * result + (getCodTypfin() == null ? 0 : this.getCodTypfin().hashCode());
		result = 37 * result + (getStockM() == null ? 0 : this.getStockM().hashCode());
		result = 37 * result + (getLibTypfin() == null ? 0 : this.getLibTypfin().hashCode());
		return result;
	}

}
