package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Detfin generated by hbm2java
 */
public class Detfin implements java.io.Serializable {

	private DetfinId id;

	public Detfin() {
	}

	public Detfin(DetfinId id) {
		this.id = id;
	}

	public DetfinId getId() {
		return this.id;
	}

	public void setId(DetfinId id) {
		this.id = id;
	}

}
