package com.gts.expersoft.models;
// Generated Mar 12, 2018 9:29:48 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * EquipeId generated by hbm2java
 */
public class Equipe implements java.io.Serializable {

	private String codEquip;
	private String libEquip;
	private String matPers;
	private String nomPers;

	public Equipe() {
	}

	public Equipe(String codEquip, String libEquip, String matPers, String nomPers) {
		this.codEquip = codEquip;
		this.libEquip = libEquip;
		this.matPers = matPers;
		this.nomPers = nomPers;
	}

	public String getCodEquip() {
		return this.codEquip;
	}

	public void setCodEquip(String codEquip) {
		this.codEquip = codEquip;
	}

	public String getLibEquip() {
		return this.libEquip;
	}

	public void setLibEquip(String libEquip) {
		this.libEquip = libEquip;
	}

	public String getMatPers() {
		return this.matPers;
	}

	public void setMatPers(String matPers) {
		this.matPers = matPers;
	}

	public String getNomPers() {
		return this.nomPers;
	}

	public void setNomPers(String nomPers) {
		this.nomPers = nomPers;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Equipe))
			return false;
		Equipe castOther = (Equipe) other;

		return ((this.getCodEquip() == castOther.getCodEquip()) || (this.getCodEquip() != null
				&& castOther.getCodEquip() != null && this.getCodEquip().equals(castOther.getCodEquip())))
				&& ((this.getLibEquip() == castOther.getLibEquip()) || (this.getLibEquip() != null
						&& castOther.getLibEquip() != null && this.getLibEquip().equals(castOther.getLibEquip())))
				&& ((this.getMatPers() == castOther.getMatPers()) || (this.getMatPers() != null
						&& castOther.getMatPers() != null && this.getMatPers().equals(castOther.getMatPers())))
				&& ((this.getNomPers() == castOther.getNomPers()) || (this.getNomPers() != null
						&& castOther.getNomPers() != null && this.getNomPers().equals(castOther.getNomPers())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodEquip() == null ? 0 : this.getCodEquip().hashCode());
		result = 37 * result + (getLibEquip() == null ? 0 : this.getLibEquip().hashCode());
		result = 37 * result + (getMatPers() == null ? 0 : this.getMatPers().hashCode());
		result = 37 * result + (getNomPers() == null ? 0 : this.getNomPers().hashCode());
		return result;
	}

}
