package com.gts.expersoft.models;
// Generated Feb 28, 2018 9:21:27 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * FarmsurfId generated by hbm2java
 */
public class Farmsurf implements java.io.Serializable {

	private String codParcel;
	private String libVil;
	private String libProd;
	private String libVar;
	private Double surface;
	private String qteBp;
	private String qteFp;
	private String qteBr;
	private String qteFr;
	private String codVil;
	private String codFarm;
	private String nameFarm;
	private String num;
	private String ins;
	private String codProd;
	private String datparc;
	private String codVar;

	public Farmsurf() {
	}

	public Farmsurf(String codParcel, String libVil, String libProd, String libVar, Double surface, String qteBp,
			String qteFp, String qteBr, String qteFr, String codVil, String codFarm, String num, String ins,
			String codProd, String datparc, String codVar) {
		this.codParcel = codParcel;
		this.libVil = libVil;
		this.libProd = libProd;
		this.libVar = libVar;
		this.surface = surface;
		this.qteBp = qteBp;
		this.qteFp = qteFp;
		this.qteBr = qteBr;
		this.qteFr = qteFr;
		this.codVil = codVil;
		this.codFarm = codFarm;
		this.num = num;
		this.ins = ins;
		this.codProd = codProd;
		this.datparc = datparc;
		this.codVar = codVar;
	}

	public String getCodParcel() {
		return this.codParcel;
	}

	public void setCodParcel(String codParcel) {
		this.codParcel = codParcel;
	}

	public String getLibVil() {
		return this.libVil;
	}

	public void setLibVil(String libVil) {
		this.libVil = libVil;
	}

	public String getLibProd() {
		return this.libProd;
	}

	public void setLibProd(String libProd) {
		this.libProd = libProd;
	}

	public String getLibVar() {
		return this.libVar;
	}

	public void setLibVar(String libVar) {
		this.libVar = libVar;
	}

	public Double getSurface() {
		return this.surface;
	}

	public void setSurface(Double surface) {
		this.surface = surface;
	}

	public String getQteBp() {
		return this.qteBp;
	}

	public void setQteBp(String qteBp) {
		this.qteBp = qteBp;
	}

	public String getQteFp() {
		return this.qteFp;
	}

	public void setQteFp(String qteFp) {
		this.qteFp = qteFp;
	}

	public String getQteBr() {
		return this.qteBr;
	}

	public void setQteBr(String qteBr) {
		this.qteBr = qteBr;
	}

	public String getQteFr() {
		return this.qteFr;
	}

	public void setQteFr(String qteFr) {
		this.qteFr = qteFr;
	}

	public String getCodVil() {
		return this.codVil;
	}

	public void setCodVil(String codVil) {
		this.codVil = codVil;
	}

	public String getCodFarm() {
		return this.codFarm;
	}

	public void setCodFarm(String codFarm) {
		this.codFarm = codFarm;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getIns() {
		return this.ins;
	}

	public void setIns(String ins) {
		this.ins = ins;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public String getDatparc() {
		return this.datparc;
	}

	public void setDatparc(String datparc) {
		this.datparc = datparc;
	}

	public String getCodVar() {
		return this.codVar;
	}

	public void setCodVar(String codVar) {
		this.codVar = codVar;
	}

	
	
	public String getNameFarm() {
		return nameFarm;
	}

	public void setNameFarm(String nameFarm) {
		this.nameFarm = nameFarm;
	}

	@Override
	public String toString() {
		return "Farmsurf [codParcel=" + codParcel + ", libVil=" + libVil + ", libProd=" + libProd + ", libVar=" + libVar
				+ ", surface=" + surface + ", qteBp=" + qteBp + ", qteFp=" + qteFp + ", qteBr=" + qteBr + ", qteFr="
				+ qteFr + ", codVil=" + codVil + ", codFarm=" + codFarm + ", num=" + num + ", ins=" + ins + ", codProd="
				+ codProd + ", datparc=" + datparc + ", codVar=" + codVar + "]";
	}

	
	

	
}
