package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Fourn generated by hbm2java
 */
public class Fourn implements java.io.Serializable {

	private FournId id;

	public Fourn() {
	}

	public Fourn(FournId id) {
		this.id = id;
	}

	public FournId getId() {
		return this.id;
	}

	public void setId(FournId id) {
		this.id = id;
	}

}
