package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * LmvtbqId generated by hbm2java
 */
public class LmvtbqId implements java.io.Serializable {

	
	private String reference;
	private String dateDoc;
	private String nocpte;
	private String libJou;
	private String libelle;
	private String nomPers;
	private String mtDebit;
	private Double mtCredit;
	private String mtSolde;
	private String codBq;
	private String noMvt;
	private String codJou;
	private String ins;
	private String num;
	private String sens;
	private String matPers;

	public LmvtbqId() {
	}

	

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDateDoc() {
		return this.dateDoc;
	}

	public void setDateDoc(String dateDoc) {
		this.dateDoc = dateDoc;
	}

	public String getNocpte() {
		return this.nocpte;
	}

	public void setNocpte(String nocpte) {
		this.nocpte = nocpte;
	}

	public String getLibJou() {
		return this.libJou;
	}

	public void setLibJou(String libJou) {
		this.libJou = libJou;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getNomPers() {
		return this.nomPers;
	}

	public void setNomPers(String nomPers) {
		this.nomPers = nomPers;
	}

	public String getMtDebit() {
		return this.mtDebit;
	}

	public void setMtDebit(String mtDebit) {
		this.mtDebit = mtDebit;
	}

	public Double getMtCredit() {
		return this.mtCredit;
	}

	public void setMtCredit(Double mtCredit) {
		this.mtCredit = mtCredit;
	}

	public String getMtSolde() {
		return this.mtSolde;
	}

	public void setMtSolde(String mtSolde) {
		this.mtSolde = mtSolde;
	}

	public String getCodBq() {
		return this.codBq;
	}

	public void setCodBq(String codBq) {
		this.codBq = codBq;
	}

	public String getNoMvt() {
		return this.noMvt;
	}

	public void setNoMvt(String noMvt) {
		this.noMvt = noMvt;
	}

	public String getCodJou() {
		return this.codJou;
	}

	public void setCodJou(String codJou) {
		this.codJou = codJou;
	}

	public String getIns() {
		return this.ins;
	}

	public void setIns(String ins) {
		this.ins = ins;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getSens() {
		return this.sens;
	}

	public void setSens(String sens) {
		this.sens = sens;
	}

	public String getMatPers() {
		return this.matPers;
	}

	public void setMatPers(String matPers) {
		this.matPers = matPers;
	}

	

	

}
