package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Lmvtbq generated by hbm2java
 */
public class Lmvtbq implements java.io.Serializable {

	private LmvtbqId id;

	public Lmvtbq() {
	}

	public Lmvtbq(LmvtbqId id) {
		this.id = id;
	}

	public LmvtbqId getId() {
		return this.id;
	}

	public void setId(LmvtbqId id) {
		this.id = id;
	}

}
