package com.gts.expersoft.models;
// Generated Mar 9, 2018 3:36:12 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * LpaletId generated by hbm2java
 */
public class Lpalet implements java.io.Serializable {

	private Integer nobe;
	private String datbe;
	private String codParcel;
	private String libVar;
	private Double qteD;
	private Double qteU;
	private Double qteR;
	private String codVar;
	private String noFich;
	private String ins;
	private Integer num;
	private Integer noPal;
	private String codCali;
	private String codQual;

	public Lpalet() {
	}

	public Lpalet(Integer nobe, String datbe, String codParcel, String libVar, Double qteD, Double qteU, Double qteR,
			String codVar, String noFich, String ins, Integer num, Integer noPal, String codCali, String codQual) {
		this.nobe = nobe;
		this.datbe = datbe;
		this.codParcel = codParcel;
		this.libVar = libVar;
		this.qteD = qteD;
		this.qteU = qteU;
		this.qteR = qteR;
		this.codVar = codVar;
		this.noFich = noFich;
		this.ins = ins;
		this.num = num;
		this.noPal = noPal;
		this.codCali = codCali;
		this.codQual = codQual;
	}

	public Integer getNobe() {
		return this.nobe;
	}

	public void setNobe(Integer nobe) {
		this.nobe = nobe;
	}

	public String getDatbe() {
		return this.datbe;
	}

	public void setDatbe(String datbe) {
		this.datbe = datbe;
	}

	public String getCodParcel() {
		return this.codParcel;
	}

	public void setCodParcel(String codParcel) {
		this.codParcel = codParcel;
	}

	public String getLibVar() {
		return this.libVar;
	}

	public void setLibVar(String libVar) {
		this.libVar = libVar;
	}

	public Double getQteD() {
		return this.qteD;
	}

	public void setQteD(Double qteD) {
		this.qteD = qteD;
	}

	public Double getQteU() {
		return this.qteU;
	}

	public void setQteU(Double qteU) {
		this.qteU = qteU;
	}

	public Double getQteR() {
		return this.qteR;
	}

	public void setQteR(Double qteR) {
		this.qteR = qteR;
	}

	public String getCodVar() {
		return this.codVar;
	}

	public void setCodVar(String codVar) {
		this.codVar = codVar;
	}

	public String getNoFich() {
		return this.noFich;
	}

	public void setNoFich(String noFich) {
		this.noFich = noFich;
	}

	public String getIns() {
		return this.ins;
	}

	public void setIns(String ins) {
		this.ins = ins;
	}

	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public Integer getNoPal() {
		return this.noPal;
	}

	public void setNoPal(Integer noPal) {
		this.noPal = noPal;
	}

	public String getCodCali() {
		return this.codCali;
	}

	public void setCodCali(String codCali) {
		this.codCali = codCali;
	}

	public String getCodQual() {
		return this.codQual;
	}

	public void setCodQual(String codQual) {
		this.codQual = codQual;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Lpalet))
			return false;
		Lpalet castOther = (Lpalet) other;

		return ((this.getNobe() == castOther.getNobe()) || (this.getNobe() != null && castOther.getNobe() != null
				&& this.getNobe().equals(castOther.getNobe())))
				&& ((this.getDatbe() == castOther.getDatbe()) || (this.getDatbe() != null
						&& castOther.getDatbe() != null && this.getDatbe().equals(castOther.getDatbe())))
				&& ((this.getCodParcel() == castOther.getCodParcel()) || (this.getCodParcel() != null
						&& castOther.getCodParcel() != null && this.getCodParcel().equals(castOther.getCodParcel())))
				&& ((this.getLibVar() == castOther.getLibVar()) || (this.getLibVar() != null
						&& castOther.getLibVar() != null && this.getLibVar().equals(castOther.getLibVar())))
				&& ((this.getQteD() == castOther.getQteD()) || (this.getQteD() != null && castOther.getQteD() != null
						&& this.getQteD().equals(castOther.getQteD())))
				&& ((this.getQteU() == castOther.getQteU()) || (this.getQteU() != null && castOther.getQteU() != null
						&& this.getQteU().equals(castOther.getQteU())))
				&& ((this.getQteR() == castOther.getQteR()) || (this.getQteR() != null && castOther.getQteR() != null
						&& this.getQteR().equals(castOther.getQteR())))
				&& ((this.getCodVar() == castOther.getCodVar()) || (this.getCodVar() != null
						&& castOther.getCodVar() != null && this.getCodVar().equals(castOther.getCodVar())))
				&& ((this.getNoFich() == castOther.getNoFich()) || (this.getNoFich() != null
						&& castOther.getNoFich() != null && this.getNoFich().equals(castOther.getNoFich())))
				&& ((this.getIns() == castOther.getIns()) || (this.getIns() != null && castOther.getIns() != null
						&& this.getIns().equals(castOther.getIns())))
				&& ((this.getNum() == castOther.getNum()) || (this.getNum() != null && castOther.getNum() != null
						&& this.getNum().equals(castOther.getNum())))
				&& ((this.getNoPal() == castOther.getNoPal()) || (this.getNoPal() != null
						&& castOther.getNoPal() != null && this.getNoPal().equals(castOther.getNoPal())))
				&& ((this.getCodCali() == castOther.getCodCali()) || (this.getCodCali() != null
						&& castOther.getCodCali() != null && this.getCodCali().equals(castOther.getCodCali())))
				&& ((this.getCodQual() == castOther.getCodQual()) || (this.getCodQual() != null
						&& castOther.getCodQual() != null && this.getCodQual().equals(castOther.getCodQual())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNobe() == null ? 0 : this.getNobe().hashCode());
		result = 37 * result + (getDatbe() == null ? 0 : this.getDatbe().hashCode());
		result = 37 * result + (getCodParcel() == null ? 0 : this.getCodParcel().hashCode());
		result = 37 * result + (getLibVar() == null ? 0 : this.getLibVar().hashCode());
		result = 37 * result + (getQteD() == null ? 0 : this.getQteD().hashCode());
		result = 37 * result + (getQteU() == null ? 0 : this.getQteU().hashCode());
		result = 37 * result + (getQteR() == null ? 0 : this.getQteR().hashCode());
		result = 37 * result + (getCodVar() == null ? 0 : this.getCodVar().hashCode());
		result = 37 * result + (getNoFich() == null ? 0 : this.getNoFich().hashCode());
		result = 37 * result + (getIns() == null ? 0 : this.getIns().hashCode());
		result = 37 * result + (getNum() == null ? 0 : this.getNum().hashCode());
		result = 37 * result + (getNoPal() == null ? 0 : this.getNoPal().hashCode());
		result = 37 * result + (getCodCali() == null ? 0 : this.getCodCali().hashCode());
		result = 37 * result + (getCodQual() == null ? 0 : this.getCodQual().hashCode());
		return result;
	}

}
