package com.gts.expersoft.models;
// Generated Mar 16, 2018 3:54:04 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * MarqueId generated by hbm2java
 */
public class Marque implements java.io.Serializable {

	private String codMarq;
	private String libProd;
	private String libMarq;
	private String codProd;
	private String abrege;
	private Integer ordre;

	public Marque() {
	}

	public Marque(String codMarq, String libProd, String libMarq, String codProd, String abrege, Integer ordre) {
		this.codMarq = codMarq;
		this.libProd = libProd;
		this.libMarq = libMarq;
		this.codProd = codProd;
		this.abrege = abrege;
		this.ordre = ordre;
	}

	public String getCodMarq() {
		return this.codMarq;
	}

	public void setCodMarq(String codMarq) {
		this.codMarq = codMarq;
	}

	public String getLibProd() {
		return this.libProd;
	}

	public void setLibProd(String libProd) {
		this.libProd = libProd;
	}

	public String getLibMarq() {
		return this.libMarq;
	}

	public void setLibMarq(String libMarq) {
		this.libMarq = libMarq;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public String getAbrege() {
		return this.abrege;
	}

	public void setAbrege(String abrege) {
		this.abrege = abrege;
	}

	public Integer getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Integer ordre) {
		this.ordre = ordre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Marque))
			return false;
		Marque castOther = (Marque) other;

		return ((this.getCodMarq() == castOther.getCodMarq()) || (this.getCodMarq() != null
				&& castOther.getCodMarq() != null && this.getCodMarq().equals(castOther.getCodMarq())))
				&& ((this.getLibProd() == castOther.getLibProd()) || (this.getLibProd() != null
						&& castOther.getLibProd() != null && this.getLibProd().equals(castOther.getLibProd())))
				&& ((this.getLibMarq() == castOther.getLibMarq()) || (this.getLibMarq() != null
						&& castOther.getLibMarq() != null && this.getLibMarq().equals(castOther.getLibMarq())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getAbrege() == castOther.getAbrege()) || (this.getAbrege() != null
						&& castOther.getAbrege() != null && this.getAbrege().equals(castOther.getAbrege())))
				&& ((this.getOrdre() == castOther.getOrdre()) || (this.getOrdre() != null
						&& castOther.getOrdre() != null && this.getOrdre().equals(castOther.getOrdre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodMarq() == null ? 0 : this.getCodMarq().hashCode());
		result = 37 * result + (getLibProd() == null ? 0 : this.getLibProd().hashCode());
		result = 37 * result + (getLibMarq() == null ? 0 : this.getLibMarq().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getAbrege() == null ? 0 : this.getAbrege().hashCode());
		result = 37 * result + (getOrdre() == null ? 0 : this.getOrdre().hashCode());
		return result;
	}

}
