package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Menus generated by hbm2java
 */
public class Menus implements java.io.Serializable {

	private int id;
	private String nom;
	private Integer menuId;
	private Integer level;
	private List<Menus> submenus;
	private boolean checked;
	
	public Menus() {
	}

	public Menus(int id) {
		this.id = id;
	}

	public Menus(int id, String nom, Integer menuId, Integer level) {
		this.id = id;
		this.nom = nom;
		this.menuId = menuId;
		this.level = level;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public List<Menus> getSubmenus() {
		return submenus;
	}

	public void setSubmenus(List<Menus> submenus) {
		this.submenus = submenus;
	}

	public boolean isChecked() {
		return checked;
	}

	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	
	

}
