package com.gts.expersoft.models;
// Generated Feb 28, 2018 9:21:27 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Nation generated by hbm2java
 */
public class Nation implements java.io.Serializable {

	private int id;
	private String codNat;
	private String libNat;
	private Set fourns = new HashSet(0);

	public Nation() {
	}

	public Nation(int id) {
		this.id = id;
	}

	public Nation(int id, String codNat, String libNat, Set fourns) {
		this.id = id;
		this.codNat = codNat;
		this.libNat = libNat;
		this.fourns = fourns;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodNat() {
		return this.codNat;
	}

	public void setCodNat(String codNat) {
		this.codNat = codNat;
	}

	public String getLibNat() {
		return this.libNat;
	}

	public void setLibNat(String libNat) {
		this.libNat = libNat;
	}

	public Set getFourns() {
		return this.fourns;
	}

	public void setFourns(Set fourns) {
		this.fourns = fourns;
	}

}
