package com.gts.expersoft.models;
// Generated Mar 9, 2018 3:36:12 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * PpaletId generated by hbm2java
 */
public class Ppalet implements java.io.Serializable {

	private Integer noPal;
	private String datpal;
	private String libStat;
	private String libCali;
	private Double qteTot;
	private String codProd;
	private Integer decision;
	private String codStat;
	private String codEquip;
	private String codMarq;
	private String codCali;
	private String datent;
	private String heurent;
	private Integer tempTc;
	private String codMag;
	private String codQual;

	public Ppalet() {
	}

	public Ppalet(Integer noPal, String datpal, String libStat, String libCali, Double qteTot, String codProd,
			Integer decision, String codStat, String codEquip, String codMarq, String codCali, String datent,
			String heurent, Integer tempTc, String codMag, String codQual) {
		this.noPal = noPal;
		this.datpal = datpal;
		this.libStat = libStat;
		this.libCali = libCali;
		this.qteTot = qteTot;
		this.codProd = codProd;
		this.decision = decision;
		this.codStat = codStat;
		this.codEquip = codEquip;
		this.codMarq = codMarq;
		this.codCali = codCali;
		this.datent = datent;
		this.heurent = heurent;
		this.tempTc = tempTc;
		this.codMag = codMag;
		this.codQual = codQual;
	}

	public Integer getNoPal() {
		return this.noPal;
	}

	public void setNoPal(Integer noPal) {
		this.noPal = noPal;
	}

	public String getDatpal() {
		return this.datpal;
	}

	public void setDatpal(String datpal) {
		this.datpal = datpal;
	}

	public String getLibStat() {
		return this.libStat;
	}

	public void setLibStat(String libStat) {
		this.libStat = libStat;
	}

	public String getLibCali() {
		return this.libCali;
	}

	public void setLibCali(String libCali) {
		this.libCali = libCali;
	}

	public Double getQteTot() {
		return this.qteTot;
	}

	public void setQteTot(Double qteTot) {
		this.qteTot = qteTot;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public Integer getDecision() {
		return this.decision;
	}

	public void setDecision(Integer decision) {
		this.decision = decision;
	}

	public String getCodStat() {
		return this.codStat;
	}

	public void setCodStat(String codStat) {
		this.codStat = codStat;
	}

	public String getCodEquip() {
		return this.codEquip;
	}

	public void setCodEquip(String codEquip) {
		this.codEquip = codEquip;
	}

	public String getCodMarq() {
		return this.codMarq;
	}

	public void setCodMarq(String codMarq) {
		this.codMarq = codMarq;
	}

	public String getCodCali() {
		return this.codCali;
	}

	public void setCodCali(String codCali) {
		this.codCali = codCali;
	}

	public String getDatent() {
		return this.datent;
	}

	public void setDatent(String datent) {
		this.datent = datent;
	}

	public String getHeurent() {
		return this.heurent;
	}

	public void setHeurent(String heurent) {
		this.heurent = heurent;
	}

	public Integer getTempTc() {
		return this.tempTc;
	}

	public void setTempTc(Integer tempTc) {
		this.tempTc = tempTc;
	}

	public String getCodMag() {
		return this.codMag;
	}

	public void setCodMag(String codMag) {
		this.codMag = codMag;
	}

	public String getCodQual() {
		return this.codQual;
	}

	public void setCodQual(String codQual) {
		this.codQual = codQual;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Ppalet))
			return false;
		Ppalet castOther = (Ppalet) other;

		return ((this.getNoPal() == castOther.getNoPal()) || (this.getNoPal() != null && castOther.getNoPal() != null
				&& this.getNoPal().equals(castOther.getNoPal())))
				&& ((this.getDatpal() == castOther.getDatpal()) || (this.getDatpal() != null
						&& castOther.getDatpal() != null && this.getDatpal().equals(castOther.getDatpal())))
				&& ((this.getLibStat() == castOther.getLibStat()) || (this.getLibStat() != null
						&& castOther.getLibStat() != null && this.getLibStat().equals(castOther.getLibStat())))
				&& ((this.getLibCali() == castOther.getLibCali()) || (this.getLibCali() != null
						&& castOther.getLibCali() != null && this.getLibCali().equals(castOther.getLibCali())))
				&& ((this.getQteTot() == castOther.getQteTot()) || (this.getQteTot() != null
						&& castOther.getQteTot() != null && this.getQteTot().equals(castOther.getQteTot())))
				&& ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
						&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getDecision() == castOther.getDecision()) || (this.getDecision() != null
						&& castOther.getDecision() != null && this.getDecision().equals(castOther.getDecision())))
				&& ((this.getCodStat() == castOther.getCodStat()) || (this.getCodStat() != null
						&& castOther.getCodStat() != null && this.getCodStat().equals(castOther.getCodStat())))
				&& ((this.getCodEquip() == castOther.getCodEquip()) || (this.getCodEquip() != null
						&& castOther.getCodEquip() != null && this.getCodEquip().equals(castOther.getCodEquip())))
				&& ((this.getCodMarq() == castOther.getCodMarq()) || (this.getCodMarq() != null
						&& castOther.getCodMarq() != null && this.getCodMarq().equals(castOther.getCodMarq())))
				&& ((this.getCodCali() == castOther.getCodCali()) || (this.getCodCali() != null
						&& castOther.getCodCali() != null && this.getCodCali().equals(castOther.getCodCali())))
				&& ((this.getDatent() == castOther.getDatent()) || (this.getDatent() != null
						&& castOther.getDatent() != null && this.getDatent().equals(castOther.getDatent())))
				&& ((this.getHeurent() == castOther.getHeurent()) || (this.getHeurent() != null
						&& castOther.getHeurent() != null && this.getHeurent().equals(castOther.getHeurent())))
				&& ((this.getTempTc() == castOther.getTempTc()) || (this.getTempTc() != null
						&& castOther.getTempTc() != null && this.getTempTc().equals(castOther.getTempTc())))
				&& ((this.getCodMag() == castOther.getCodMag()) || (this.getCodMag() != null
						&& castOther.getCodMag() != null && this.getCodMag().equals(castOther.getCodMag())))
				&& ((this.getCodQual() == castOther.getCodQual()) || (this.getCodQual() != null
						&& castOther.getCodQual() != null && this.getCodQual().equals(castOther.getCodQual())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNoPal() == null ? 0 : this.getNoPal().hashCode());
		result = 37 * result + (getDatpal() == null ? 0 : this.getDatpal().hashCode());
		result = 37 * result + (getLibStat() == null ? 0 : this.getLibStat().hashCode());
		result = 37 * result + (getLibCali() == null ? 0 : this.getLibCali().hashCode());
		result = 37 * result + (getQteTot() == null ? 0 : this.getQteTot().hashCode());
		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getDecision() == null ? 0 : this.getDecision().hashCode());
		result = 37 * result + (getCodStat() == null ? 0 : this.getCodStat().hashCode());
		result = 37 * result + (getCodEquip() == null ? 0 : this.getCodEquip().hashCode());
		result = 37 * result + (getCodMarq() == null ? 0 : this.getCodMarq().hashCode());
		result = 37 * result + (getCodCali() == null ? 0 : this.getCodCali().hashCode());
		result = 37 * result + (getDatent() == null ? 0 : this.getDatent().hashCode());
		result = 37 * result + (getHeurent() == null ? 0 : this.getHeurent().hashCode());
		result = 37 * result + (getTempTc() == null ? 0 : this.getTempTc().hashCode());
		result = 37 * result + (getCodMag() == null ? 0 : this.getCodMag().hashCode());
		result = 37 * result + (getCodQual() == null ? 0 : this.getCodQual().hashCode());
		return result;
	}

}
