package com.gts.expersoft.models;
// Generated Feb 28, 2018 9:21:27 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * PrefectId generated by hbm2java
 */
public class Prefect implements java.io.Serializable {

	private String codPref;
	private String libRegion;
	private String libPref;
	private String codRegion;
	private Double longGps;
	private Double latiGps;

	public Prefect() {
	}

	public Prefect(String codPref, String libRegion, String libPref, String codRegion, Double longGps,
			Double latiGps) {
		this.codPref = codPref;
		this.libRegion = libRegion;
		this.libPref = libPref;
		this.codRegion = codRegion;
		this.longGps = longGps;
		this.latiGps = latiGps;
	}

	public String getCodPref() {
		return this.codPref;
	}

	public void setCodPref(String codPref) {
		this.codPref = codPref;
	}

	public String getLibRegion() {
		return this.libRegion;
	}

	public void setLibRegion(String libRegion) {
		this.libRegion = libRegion;
	}

	public String getLibPref() {
		return this.libPref;
	}

	public void setLibPref(String libPref) {
		this.libPref = libPref;
	}

	public String getCodRegion() {
		return this.codRegion;
	}

	public void setCodRegion(String codRegion) {
		this.codRegion = codRegion;
	}

	public Double getLongGps() {
		return this.longGps;
	}

	public void setLongGps(Double longGps) {
		this.longGps = longGps;
	}

	public Double getLatiGps() {
		return this.latiGps;
	}

	public void setLatiGps(Double latiGps) {
		this.latiGps = latiGps;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Prefect))
			return false;
		Prefect castOther = (Prefect) other;

		return ((this.getCodPref() == castOther.getCodPref()) || (this.getCodPref() != null
				&& castOther.getCodPref() != null && this.getCodPref().equals(castOther.getCodPref())))
				&& ((this.getLibRegion() == castOther.getLibRegion()) || (this.getLibRegion() != null
						&& castOther.getLibRegion() != null && this.getLibRegion().equals(castOther.getLibRegion())))
				&& ((this.getLibPref() == castOther.getLibPref()) || (this.getLibPref() != null
						&& castOther.getLibPref() != null && this.getLibPref().equals(castOther.getLibPref())))
				&& ((this.getCodRegion() == castOther.getCodRegion()) || (this.getCodRegion() != null
						&& castOther.getCodRegion() != null && this.getCodRegion().equals(castOther.getCodRegion())))
				&& ((this.getLongGps() == castOther.getLongGps()) || (this.getLongGps() != null
						&& castOther.getLongGps() != null && this.getLongGps().equals(castOther.getLongGps())))
				&& ((this.getLatiGps() == castOther.getLatiGps()) || (this.getLatiGps() != null
						&& castOther.getLatiGps() != null && this.getLatiGps().equals(castOther.getLatiGps())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodPref() == null ? 0 : this.getCodPref().hashCode());
		result = 37 * result + (getLibRegion() == null ? 0 : this.getLibRegion().hashCode());
		result = 37 * result + (getLibPref() == null ? 0 : this.getLibPref().hashCode());
		result = 37 * result + (getCodRegion() == null ? 0 : this.getCodRegion().hashCode());
		result = 37 * result + (getLongGps() == null ? 0 : this.getLongGps().hashCode());
		result = 37 * result + (getLatiGps() == null ? 0 : this.getLatiGps().hashCode());
		return result;
	}

}
