package com.gts.expersoft.models;
// Generated Jan 28, 2018 8:59:49 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ProduitId generated by hbm2java
 */
public class ProduitId implements java.io.Serializable {

	private String codProd;
	private String libProd;
	private String pnobe;
	private Integer noBe;
	private Integer noBs;
	private String pnobs;
	private Double bic;
	private String cptAch;
	private String cptVte;
	private String cptBic;
	private String codUom;
	private String codUom2;
	private Double puFarm;
	private Double puFou;

	public ProduitId() {
	}

	public ProduitId(String codProd, String libProd, String pnobe, Integer noBe, Integer noBs, String pnobs, Double bic,
			String cptAch, String cptVte, String cptBic, String codUom, String codUom2, Double puFarm, Double puFou) {
		this.codProd = codProd;
		this.libProd = libProd;
		this.pnobe = pnobe;
		this.noBe = noBe;
		this.noBs = noBs;
		this.pnobs = pnobs;
		this.bic = bic;
		this.cptAch = cptAch;
		this.cptVte = cptVte;
		this.cptBic = cptBic;
		this.codUom = codUom;
		this.codUom2 = codUom2;
		this.puFarm = puFarm;
		this.puFou = puFou;
	}

	public String getCodProd() {
		return this.codProd;
	}

	public void setCodProd(String codProd) {
		this.codProd = codProd;
	}

	public String getLibProd() {
		return this.libProd;
	}

	public void setLibProd(String libProd) {
		this.libProd = libProd;
	}

	public String getPnobe() {
		return this.pnobe;
	}

	public void setPnobe(String pnobe) {
		this.pnobe = pnobe;
	}

	public Integer getNoBe() {
		return this.noBe;
	}

	public void setNoBe(Integer noBe) {
		this.noBe = noBe;
	}

	public Integer getNoBs() {
		return this.noBs;
	}

	public void setNoBs(Integer noBs) {
		this.noBs = noBs;
	}

	public String getPnobs() {
		return this.pnobs;
	}

	public void setPnobs(String pnobs) {
		this.pnobs = pnobs;
	}

	public Double getBic() {
		return this.bic;
	}

	public void setBic(Double bic) {
		this.bic = bic;
	}

	public String getCptAch() {
		return this.cptAch;
	}

	public void setCptAch(String cptAch) {
		this.cptAch = cptAch;
	}

	public String getCptVte() {
		return this.cptVte;
	}

	public void setCptVte(String cptVte) {
		this.cptVte = cptVte;
	}

	public String getCptBic() {
		return this.cptBic;
	}

	public void setCptBic(String cptBic) {
		this.cptBic = cptBic;
	}

	public String getCodUom() {
		return this.codUom;
	}

	public void setCodUom(String codUom) {
		this.codUom = codUom;
	}

	public String getCodUom2() {
		return this.codUom2;
	}

	public void setCodUom2(String codUom2) {
		this.codUom2 = codUom2;
	}

	public Double getPuFarm() {
		return this.puFarm;
	}

	public void setPuFarm(Double puFarm) {
		this.puFarm = puFarm;
	}

	public Double getPuFou() {
		return this.puFou;
	}

	public void setPuFou(Double puFou) {
		this.puFou = puFou;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProduitId))
			return false;
		ProduitId castOther = (ProduitId) other;

		return ((this.getCodProd() == castOther.getCodProd()) || (this.getCodProd() != null
				&& castOther.getCodProd() != null && this.getCodProd().equals(castOther.getCodProd())))
				&& ((this.getLibProd() == castOther.getLibProd()) || (this.getLibProd() != null
						&& castOther.getLibProd() != null && this.getLibProd().equals(castOther.getLibProd())))
				&& ((this.getPnobe() == castOther.getPnobe()) || (this.getPnobe() != null
						&& castOther.getPnobe() != null && this.getPnobe().equals(castOther.getPnobe())))
				&& ((this.getNoBe() == castOther.getNoBe()) || (this.getNoBe() != null && castOther.getNoBe() != null
						&& this.getNoBe().equals(castOther.getNoBe())))
				&& ((this.getNoBs() == castOther.getNoBs()) || (this.getNoBs() != null && castOther.getNoBs() != null
						&& this.getNoBs().equals(castOther.getNoBs())))
				&& ((this.getPnobs() == castOther.getPnobs()) || (this.getPnobs() != null
						&& castOther.getPnobs() != null && this.getPnobs().equals(castOther.getPnobs())))
				&& ((this.getBic() == castOther.getBic()) || (this.getBic() != null && castOther.getBic() != null
						&& this.getBic().equals(castOther.getBic())))
				&& ((this.getCptAch() == castOther.getCptAch()) || (this.getCptAch() != null
						&& castOther.getCptAch() != null && this.getCptAch().equals(castOther.getCptAch())))
				&& ((this.getCptVte() == castOther.getCptVte()) || (this.getCptVte() != null
						&& castOther.getCptVte() != null && this.getCptVte().equals(castOther.getCptVte())))
				&& ((this.getCptBic() == castOther.getCptBic()) || (this.getCptBic() != null
						&& castOther.getCptBic() != null && this.getCptBic().equals(castOther.getCptBic())))
				&& ((this.getCodUom() == castOther.getCodUom()) || (this.getCodUom() != null
						&& castOther.getCodUom() != null && this.getCodUom().equals(castOther.getCodUom())))
				&& ((this.getCodUom2() == castOther.getCodUom2()) || (this.getCodUom2() != null
						&& castOther.getCodUom2() != null && this.getCodUom2().equals(castOther.getCodUom2())))
				&& ((this.getPuFarm() == castOther.getPuFarm()) || (this.getPuFarm() != null
						&& castOther.getPuFarm() != null && this.getPuFarm().equals(castOther.getPuFarm())))
				&& ((this.getPuFou() == castOther.getPuFou()) || (this.getPuFou() != null
						&& castOther.getPuFou() != null && this.getPuFou().equals(castOther.getPuFou())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodProd() == null ? 0 : this.getCodProd().hashCode());
		result = 37 * result + (getLibProd() == null ? 0 : this.getLibProd().hashCode());
		result = 37 * result + (getPnobe() == null ? 0 : this.getPnobe().hashCode());
		result = 37 * result + (getNoBe() == null ? 0 : this.getNoBe().hashCode());
		result = 37 * result + (getNoBs() == null ? 0 : this.getNoBs().hashCode());
		result = 37 * result + (getPnobs() == null ? 0 : this.getPnobs().hashCode());
		result = 37 * result + (getBic() == null ? 0 : this.getBic().hashCode());
		result = 37 * result + (getCptAch() == null ? 0 : this.getCptAch().hashCode());
		result = 37 * result + (getCptVte() == null ? 0 : this.getCptVte().hashCode());
		result = 37 * result + (getCptBic() == null ? 0 : this.getCptBic().hashCode());
		result = 37 * result + (getCodUom() == null ? 0 : this.getCodUom().hashCode());
		result = 37 * result + (getCodUom2() == null ? 0 : this.getCodUom2().hashCode());
		result = 37 * result + (getPuFarm() == null ? 0 : this.getPuFarm().hashCode());
		result = 37 * result + (getPuFou() == null ? 0 : this.getPuFou().hashCode());
		return result;
	}

}
