package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private Integer id;
	private String code;
	private String nom;
	private List<Menus> menuses = new ArrayList<Menus>();

	public Profile() {
	}

	public Profile(String code, String nom) {
		this.code = code;
		this.nom = nom;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public List<Menus> getMenuses() {
		return menuses;
	}

	public void setMenuses(List<Menus> menuses) {
		this.menuses = menuses;
	}

	

}
