package com.gts.expersoft.models;
// Generated Feb 21, 2018 5:37:00 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private int id;
	private String codRegion;
	private String libRegion;
	private double latiGps;
	private double longGps;

	public Region() {
	}

	public Region(int id) {
		this.id = id;
	}

	public Region(int id, String codRegion, String libRegion, double latiGps, double longGps) {
		this.id = id;
		this.codRegion = codRegion;
		this.libRegion = libRegion;
		this.latiGps = latiGps;
		this.longGps = longGps;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodRegion() {
		return this.codRegion;
	}

	public void setCodRegion(String codRegion) {
		this.codRegion = codRegion;
	}

	public String getLibRegion() {
		return this.libRegion;
	}

	public void setLibRegion(String libRegion) {
		this.libRegion = libRegion;
	}

	public double getLatiGps() {
		return this.latiGps;
	}

	public void setLatiGps(double latiGps) {
		this.latiGps = latiGps;
	}

	public double getLongGps() {
		return this.longGps;
	}

	public void setLongGps(double longGps) {
		this.longGps = longGps;
	}

}
