package com.gts.expersoft.models;
// Generated Feb 28, 2018 9:21:27 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * SprefectId generated by hbm2java
 */
public class Sprefect implements java.io.Serializable {

	private String codSpref;
	private String libPref;
	private String libSpref;
	private String codPref;
	private Double longGps;
	private Double latiGps;

	public Sprefect() {
	}

	public Sprefect(String codSpref, String libPref, String libSpref, String codPref, Double longGps,
			Double latiGps) {
		this.codSpref = codSpref;
		this.libPref = libPref;
		this.libSpref = libSpref;
		this.codPref = codPref;
		this.longGps = longGps;
		this.latiGps = latiGps;
	}

	public String getCodSpref() {
		return this.codSpref;
	}

	public void setCodSpref(String codSpref) {
		this.codSpref = codSpref;
	}

	public String getLibPref() {
		return this.libPref;
	}

	public void setLibPref(String libPref) {
		this.libPref = libPref;
	}

	public String getLibSpref() {
		return this.libSpref;
	}

	public void setLibSpref(String libSpref) {
		this.libSpref = libSpref;
	}

	public String getCodPref() {
		return this.codPref;
	}

	public void setCodPref(String codPref) {
		this.codPref = codPref;
	}

	public Double getLongGps() {
		return this.longGps;
	}

	public void setLongGps(Double longGps) {
		this.longGps = longGps;
	}

	public Double getLatiGps() {
		return this.latiGps;
	}

	public void setLatiGps(Double latiGps) {
		this.latiGps = latiGps;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Sprefect))
			return false;
		Sprefect castOther = (Sprefect) other;

		return ((this.getCodSpref() == castOther.getCodSpref()) || (this.getCodSpref() != null
				&& castOther.getCodSpref() != null && this.getCodSpref().equals(castOther.getCodSpref())))
				&& ((this.getLibPref() == castOther.getLibPref()) || (this.getLibPref() != null
						&& castOther.getLibPref() != null && this.getLibPref().equals(castOther.getLibPref())))
				&& ((this.getLibSpref() == castOther.getLibSpref()) || (this.getLibSpref() != null
						&& castOther.getLibSpref() != null && this.getLibSpref().equals(castOther.getLibSpref())))
				&& ((this.getCodPref() == castOther.getCodPref()) || (this.getCodPref() != null
						&& castOther.getCodPref() != null && this.getCodPref().equals(castOther.getCodPref())))
				&& ((this.getLongGps() == castOther.getLongGps()) || (this.getLongGps() != null
						&& castOther.getLongGps() != null && this.getLongGps().equals(castOther.getLongGps())))
				&& ((this.getLatiGps() == castOther.getLatiGps()) || (this.getLatiGps() != null
						&& castOther.getLatiGps() != null && this.getLatiGps().equals(castOther.getLatiGps())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodSpref() == null ? 0 : this.getCodSpref().hashCode());
		result = 37 * result + (getLibPref() == null ? 0 : this.getLibPref().hashCode());
		result = 37 * result + (getLibSpref() == null ? 0 : this.getLibSpref().hashCode());
		result = 37 * result + (getCodPref() == null ? 0 : this.getCodPref().hashCode());
		result = 37 * result + (getLongGps() == null ? 0 : this.getLongGps().hashCode());
		result = 37 * result + (getLatiGps() == null ? 0 : this.getLatiGps().hashCode());
		return result;
	}

}
