package com.gts.expersoft.models;
// Generated Mar 11, 2018 6:30:01 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * TranspId generated by hbm2java
 */
public class Transp implements java.io.Serializable {

	private String codTrans;
	private String libTrans;
	private String nocc;
	private String norc;
	private String cptTrans;
	private String agrement;
	private String adrTrans;
	private String telTrans;
	private String faxTrans;
	private String mailTrans;
	private String codTypc;
	private Integer bic;
	private String codUt;
	private String dateAdd;
	private String dateEdit;
	private String datentre;
	private String nocptBq;
	private String nomBq;

	public Transp() {
	}

	public Transp(String codTrans, String libTrans, String nocc, String norc, String cptTrans, String agrement,
			String adrTrans, String telTrans, String faxTrans, String mailTrans, String codTypc, Integer bic,
			String codUt, String dateAdd, String dateEdit, String datentre, String nocptBq, String nomBq) {
		this.codTrans = codTrans;
		this.libTrans = libTrans;
		this.nocc = nocc;
		this.norc = norc;
		this.cptTrans = cptTrans;
		this.agrement = agrement;
		this.adrTrans = adrTrans;
		this.telTrans = telTrans;
		this.faxTrans = faxTrans;
		this.mailTrans = mailTrans;
		this.codTypc = codTypc;
		this.bic = bic;
		this.codUt = codUt;
		this.dateAdd = dateAdd;
		this.dateEdit = dateEdit;
		this.datentre = datentre;
		this.nocptBq = nocptBq;
		this.nomBq = nomBq;
	}

	public String getCodTrans() {
		return this.codTrans;
	}

	public void setCodTrans(String codTrans) {
		this.codTrans = codTrans;
	}

	public String getLibTrans() {
		return this.libTrans;
	}

	public void setLibTrans(String libTrans) {
		this.libTrans = libTrans;
	}

	public String getNocc() {
		return this.nocc;
	}

	public void setNocc(String nocc) {
		this.nocc = nocc;
	}

	public String getNorc() {
		return this.norc;
	}

	public void setNorc(String norc) {
		this.norc = norc;
	}

	public String getCptTrans() {
		return this.cptTrans;
	}

	public void setCptTrans(String cptTrans) {
		this.cptTrans = cptTrans;
	}

	public String getAgrement() {
		return this.agrement;
	}

	public void setAgrement(String agrement) {
		this.agrement = agrement;
	}

	public String getAdrTrans() {
		return this.adrTrans;
	}

	public void setAdrTrans(String adrTrans) {
		this.adrTrans = adrTrans;
	}

	public String getTelTrans() {
		return this.telTrans;
	}

	public void setTelTrans(String telTrans) {
		this.telTrans = telTrans;
	}

	public String getFaxTrans() {
		return this.faxTrans;
	}

	public void setFaxTrans(String faxTrans) {
		this.faxTrans = faxTrans;
	}

	public String getMailTrans() {
		return this.mailTrans;
	}

	public void setMailTrans(String mailTrans) {
		this.mailTrans = mailTrans;
	}

	public String getCodTypc() {
		return this.codTypc;
	}

	public void setCodTypc(String codTypc) {
		this.codTypc = codTypc;
	}

	public Integer getBic() {
		return this.bic;
	}

	public void setBic(Integer bic) {
		this.bic = bic;
	}

	public String getCodUt() {
		return this.codUt;
	}

	public void setCodUt(String codUt) {
		this.codUt = codUt;
	}

	public String getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(String dateAdd) {
		this.dateAdd = dateAdd;
	}

	public String getDateEdit() {
		return this.dateEdit;
	}

	public void setDateEdit(String dateEdit) {
		this.dateEdit = dateEdit;
	}

	public String getDatentre() {
		return this.datentre;
	}

	public void setDatentre(String datentre) {
		this.datentre = datentre;
	}

	public String getNocptBq() {
		return this.nocptBq;
	}

	public void setNocptBq(String nocptBq) {
		this.nocptBq = nocptBq;
	}

	public String getNomBq() {
		return this.nomBq;
	}

	public void setNomBq(String nomBq) {
		this.nomBq = nomBq;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Transp))
			return false;
		Transp castOther = (Transp) other;

		return ((this.getCodTrans() == castOther.getCodTrans()) || (this.getCodTrans() != null
				&& castOther.getCodTrans() != null && this.getCodTrans().equals(castOther.getCodTrans())))
				&& ((this.getLibTrans() == castOther.getLibTrans()) || (this.getLibTrans() != null
						&& castOther.getLibTrans() != null && this.getLibTrans().equals(castOther.getLibTrans())))
				&& ((this.getNocc() == castOther.getNocc()) || (this.getNocc() != null && castOther.getNocc() != null
						&& this.getNocc().equals(castOther.getNocc())))
				&& ((this.getNorc() == castOther.getNorc()) || (this.getNorc() != null && castOther.getNorc() != null
						&& this.getNorc().equals(castOther.getNorc())))
				&& ((this.getCptTrans() == castOther.getCptTrans()) || (this.getCptTrans() != null
						&& castOther.getCptTrans() != null && this.getCptTrans().equals(castOther.getCptTrans())))
				&& ((this.getAgrement() == castOther.getAgrement()) || (this.getAgrement() != null
						&& castOther.getAgrement() != null && this.getAgrement().equals(castOther.getAgrement())))
				&& ((this.getAdrTrans() == castOther.getAdrTrans()) || (this.getAdrTrans() != null
						&& castOther.getAdrTrans() != null && this.getAdrTrans().equals(castOther.getAdrTrans())))
				&& ((this.getTelTrans() == castOther.getTelTrans()) || (this.getTelTrans() != null
						&& castOther.getTelTrans() != null && this.getTelTrans().equals(castOther.getTelTrans())))
				&& ((this.getFaxTrans() == castOther.getFaxTrans()) || (this.getFaxTrans() != null
						&& castOther.getFaxTrans() != null && this.getFaxTrans().equals(castOther.getFaxTrans())))
				&& ((this.getMailTrans() == castOther.getMailTrans()) || (this.getMailTrans() != null
						&& castOther.getMailTrans() != null && this.getMailTrans().equals(castOther.getMailTrans())))
				&& ((this.getCodTypc() == castOther.getCodTypc()) || (this.getCodTypc() != null
						&& castOther.getCodTypc() != null && this.getCodTypc().equals(castOther.getCodTypc())))
				&& ((this.getBic() == castOther.getBic()) || (this.getBic() != null && castOther.getBic() != null
						&& this.getBic().equals(castOther.getBic())))
				&& ((this.getCodUt() == castOther.getCodUt()) || (this.getCodUt() != null
						&& castOther.getCodUt() != null && this.getCodUt().equals(castOther.getCodUt())))
				&& ((this.getDateAdd() == castOther.getDateAdd()) || (this.getDateAdd() != null
						&& castOther.getDateAdd() != null && this.getDateAdd().equals(castOther.getDateAdd())))
				&& ((this.getDateEdit() == castOther.getDateEdit()) || (this.getDateEdit() != null
						&& castOther.getDateEdit() != null && this.getDateEdit().equals(castOther.getDateEdit())))
				&& ((this.getDatentre() == castOther.getDatentre()) || (this.getDatentre() != null
						&& castOther.getDatentre() != null && this.getDatentre().equals(castOther.getDatentre())))
				&& ((this.getNocptBq() == castOther.getNocptBq()) || (this.getNocptBq() != null
						&& castOther.getNocptBq() != null && this.getNocptBq().equals(castOther.getNocptBq())))
				&& ((this.getNomBq() == castOther.getNomBq()) || (this.getNomBq() != null
						&& castOther.getNomBq() != null && this.getNomBq().equals(castOther.getNomBq())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodTrans() == null ? 0 : this.getCodTrans().hashCode());
		result = 37 * result + (getLibTrans() == null ? 0 : this.getLibTrans().hashCode());
		result = 37 * result + (getNocc() == null ? 0 : this.getNocc().hashCode());
		result = 37 * result + (getNorc() == null ? 0 : this.getNorc().hashCode());
		result = 37 * result + (getCptTrans() == null ? 0 : this.getCptTrans().hashCode());
		result = 37 * result + (getAgrement() == null ? 0 : this.getAgrement().hashCode());
		result = 37 * result + (getAdrTrans() == null ? 0 : this.getAdrTrans().hashCode());
		result = 37 * result + (getTelTrans() == null ? 0 : this.getTelTrans().hashCode());
		result = 37 * result + (getFaxTrans() == null ? 0 : this.getFaxTrans().hashCode());
		result = 37 * result + (getMailTrans() == null ? 0 : this.getMailTrans().hashCode());
		result = 37 * result + (getCodTypc() == null ? 0 : this.getCodTypc().hashCode());
		result = 37 * result + (getBic() == null ? 0 : this.getBic().hashCode());
		result = 37 * result + (getCodUt() == null ? 0 : this.getCodUt().hashCode());
		result = 37 * result + (getDateAdd() == null ? 0 : this.getDateAdd().hashCode());
		result = 37 * result + (getDateEdit() == null ? 0 : this.getDateEdit().hashCode());
		result = 37 * result + (getDatentre() == null ? 0 : this.getDatentre().hashCode());
		result = 37 * result + (getNocptBq() == null ? 0 : this.getNocptBq().hashCode());
		result = 37 * result + (getNomBq() == null ? 0 : this.getNomBq().hashCode());
		return result;
	}

}
