package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Uom generated by hbm2java
 */
public class Uom implements java.io.Serializable {

	private int id;
	private String libUom;
	private Double qtePackin;
	private String codUom;

	public Uom() {
	}

	public Uom(int id) {
		this.id = id;
	}

	public Uom(int id, String libUom, Double qtePackin, String codUom) {
		this.id = id;
		this.libUom = libUom;
		this.qtePackin = qtePackin;
		this.codUom = codUom;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibUom() {
		return this.libUom;
	}

	public void setLibUom(String libUom) {
		this.libUom = libUom;
	}

	public Double getQtePackin() {
		return this.qtePackin;
	}

	public void setQtePackin(Double qtePackin) {
		this.qtePackin = qtePackin;
	}

	public String getCodUom() {
		return this.codUom;
	}

	public void setCodUom(String codUom) {
		this.codUom = codUom;
	}

}
