package com.gts.expersoft.models;
// Generated Feb 21, 2018 10:30:28 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Variete generated by hbm2java
 */
public class Variete implements java.io.Serializable {

	private VarieteId id;
	
	public Variete() {
	}

	public Variete(VarieteId id) {
		this.id = id;
	}

	public VarieteId getId() {
		return this.id;
	}

	public void setId(VarieteId id) {
		this.id = id;
	}

}
