package com.gts.expersoft.models;
// Generated Feb 21, 2018 2:23:02 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * ZoneId generated by hbm2java
 */
public class ZoneId implements java.io.Serializable {

	private String codZone;
	private String libZone;
	private String matPers;
	private String nomCz;
	private String codDr;
	private String libDr;
	private Integer prevision;
	private Integer prevMb;
	private String prefixe;
	private Integer noFou;
	private Integer nolivintzv;
	private Integer nolivintzd;
	private Integer nofinFo;
	private Integer noregFo;
	private Integer nofactCl;
	private Integer nolivintza;
	private Integer noVil;
	private String nomAf;
	private String matPers2;
	private String prefVil;
	private Integer noSect;
	private String prefSect;
	private Integer nolivpv;
	private Double bonus1;
	private Double bonus2;
	private Integer nolivretus;
	private Integer noCodfarm;
	private Integer noInitz;
	private Integer nbreFarm;
	private Double surfPrev;
	private Double surfReal;
	private Double creditAnt;
	private Double credEchn0;
	private Double credEchn;
	private Double credMat;
	private Double credTotc;
	private Double credEchn1;
	private Double credTotg;
	private Integer noautRg;
	private Integer notrRg;
	private Integer id;

	public ZoneId() {
	}

	public ZoneId(String codZone, String libZone, String matPers, String nomCz, String codDr, String libDr,
			Integer prevision, Integer prevMb, String prefixe, Integer noFou, Integer nolivintzv, Integer nolivintzd,
			Integer nofinFo, Integer noregFo, Integer nofactCl, Integer nolivintza, Integer noVil, String nomAf,
			String matPers2, String prefVil, Integer noSect, String prefSect, Integer nolivpv, Double bonus1,
			Double bonus2, Integer nolivretus, Integer noCodfarm, Integer noInitz, Integer nbreFarm, Double surfPrev,
			Double surfReal, Double creditAnt, Double credEchn0, Double credEchn, Double credMat, Double credTotc,
			Double credEchn1, Double credTotg, Integer noautRg, Integer notrRg, Integer id) {
		this.codZone = codZone;
		this.libZone = libZone;
		this.matPers = matPers;
		this.nomCz = nomCz;
		this.codDr = codDr;
		this.libDr = libDr;
		this.prevision = prevision;
		this.prevMb = prevMb;
		this.prefixe = prefixe;
		this.noFou = noFou;
		this.nolivintzv = nolivintzv;
		this.nolivintzd = nolivintzd;
		this.nofinFo = nofinFo;
		this.noregFo = noregFo;
		this.nofactCl = nofactCl;
		this.nolivintza = nolivintza;
		this.noVil = noVil;
		this.nomAf = nomAf;
		this.matPers2 = matPers2;
		this.prefVil = prefVil;
		this.noSect = noSect;
		this.prefSect = prefSect;
		this.nolivpv = nolivpv;
		this.bonus1 = bonus1;
		this.bonus2 = bonus2;
		this.nolivretus = nolivretus;
		this.noCodfarm = noCodfarm;
		this.noInitz = noInitz;
		this.nbreFarm = nbreFarm;
		this.surfPrev = surfPrev;
		this.surfReal = surfReal;
		this.creditAnt = creditAnt;
		this.credEchn0 = credEchn0;
		this.credEchn = credEchn;
		this.credMat = credMat;
		this.credTotc = credTotc;
		this.credEchn1 = credEchn1;
		this.credTotg = credTotg;
		this.noautRg = noautRg;
		this.notrRg = notrRg;
		this.id = id;
	}

	public String getCodZone() {
		return this.codZone;
	}

	public void setCodZone(String codZone) {
		this.codZone = codZone;
	}

	public String getLibZone() {
		return this.libZone;
	}

	public void setLibZone(String libZone) {
		this.libZone = libZone;
	}

	public String getMatPers() {
		return this.matPers;
	}

	public void setMatPers(String matPers) {
		this.matPers = matPers;
	}

	public String getNomCz() {
		return this.nomCz;
	}

	public void setNomCz(String nomCz) {
		this.nomCz = nomCz;
	}

	public String getCodDr() {
		return this.codDr;
	}

	public void setCodDr(String codDr) {
		this.codDr = codDr;
	}

	public String getLibDr() {
		return this.libDr;
	}

	public void setLibDr(String libDr) {
		this.libDr = libDr;
	}

	public Integer getPrevision() {
		return this.prevision;
	}

	public void setPrevision(Integer prevision) {
		this.prevision = prevision;
	}

	public Integer getPrevMb() {
		return this.prevMb;
	}

	public void setPrevMb(Integer prevMb) {
		this.prevMb = prevMb;
	}

	public String getPrefixe() {
		return this.prefixe;
	}

	public void setPrefixe(String prefixe) {
		this.prefixe = prefixe;
	}

	public Integer getNoFou() {
		return this.noFou;
	}

	public void setNoFou(Integer noFou) {
		this.noFou = noFou;
	}

	public Integer getNolivintzv() {
		return this.nolivintzv;
	}

	public void setNolivintzv(Integer nolivintzv) {
		this.nolivintzv = nolivintzv;
	}

	public Integer getNolivintzd() {
		return this.nolivintzd;
	}

	public void setNolivintzd(Integer nolivintzd) {
		this.nolivintzd = nolivintzd;
	}

	public Integer getNofinFo() {
		return this.nofinFo;
	}

	public void setNofinFo(Integer nofinFo) {
		this.nofinFo = nofinFo;
	}

	public Integer getNoregFo() {
		return this.noregFo;
	}

	public void setNoregFo(Integer noregFo) {
		this.noregFo = noregFo;
	}

	public Integer getNofactCl() {
		return this.nofactCl;
	}

	public void setNofactCl(Integer nofactCl) {
		this.nofactCl = nofactCl;
	}

	public Integer getNolivintza() {
		return this.nolivintza;
	}

	public void setNolivintza(Integer nolivintza) {
		this.nolivintza = nolivintza;
	}

	public Integer getNoVil() {
		return this.noVil;
	}

	public void setNoVil(Integer noVil) {
		this.noVil = noVil;
	}

	public String getNomAf() {
		return this.nomAf;
	}

	public void setNomAf(String nomAf) {
		this.nomAf = nomAf;
	}

	public String getMatPers2() {
		return this.matPers2;
	}

	public void setMatPers2(String matPers2) {
		this.matPers2 = matPers2;
	}

	public String getPrefVil() {
		return this.prefVil;
	}

	public void setPrefVil(String prefVil) {
		this.prefVil = prefVil;
	}

	public Integer getNoSect() {
		return this.noSect;
	}

	public void setNoSect(Integer noSect) {
		this.noSect = noSect;
	}

	public String getPrefSect() {
		return this.prefSect;
	}

	public void setPrefSect(String prefSect) {
		this.prefSect = prefSect;
	}

	public Integer getNolivpv() {
		return this.nolivpv;
	}

	public void setNolivpv(Integer nolivpv) {
		this.nolivpv = nolivpv;
	}

	public Double getBonus1() {
		return this.bonus1;
	}

	public void setBonus1(Double bonus1) {
		this.bonus1 = bonus1;
	}

	public Double getBonus2() {
		return this.bonus2;
	}

	public void setBonus2(Double bonus2) {
		this.bonus2 = bonus2;
	}

	public Integer getNolivretus() {
		return this.nolivretus;
	}

	public void setNolivretus(Integer nolivretus) {
		this.nolivretus = nolivretus;
	}

	public Integer getNoCodfarm() {
		return this.noCodfarm;
	}

	public void setNoCodfarm(Integer noCodfarm) {
		this.noCodfarm = noCodfarm;
	}

	public Integer getNoInitz() {
		return this.noInitz;
	}

	public void setNoInitz(Integer noInitz) {
		this.noInitz = noInitz;
	}

	public Integer getNbreFarm() {
		return this.nbreFarm;
	}

	public void setNbreFarm(Integer nbreFarm) {
		this.nbreFarm = nbreFarm;
	}

	public Double getSurfPrev() {
		return this.surfPrev;
	}

	public void setSurfPrev(Double surfPrev) {
		this.surfPrev = surfPrev;
	}

	public Double getSurfReal() {
		return this.surfReal;
	}

	public void setSurfReal(Double surfReal) {
		this.surfReal = surfReal;
	}

	public Double getCreditAnt() {
		return this.creditAnt;
	}

	public void setCreditAnt(Double creditAnt) {
		this.creditAnt = creditAnt;
	}

	public Double getCredEchn0() {
		return this.credEchn0;
	}

	public void setCredEchn0(Double credEchn0) {
		this.credEchn0 = credEchn0;
	}

	public Double getCredEchn() {
		return this.credEchn;
	}

	public void setCredEchn(Double credEchn) {
		this.credEchn = credEchn;
	}

	public Double getCredMat() {
		return this.credMat;
	}

	public void setCredMat(Double credMat) {
		this.credMat = credMat;
	}

	public Double getCredTotc() {
		return this.credTotc;
	}

	public void setCredTotc(Double credTotc) {
		this.credTotc = credTotc;
	}

	public Double getCredEchn1() {
		return this.credEchn1;
	}

	public void setCredEchn1(Double credEchn1) {
		this.credEchn1 = credEchn1;
	}

	public Double getCredTotg() {
		return this.credTotg;
	}

	public void setCredTotg(Double credTotg) {
		this.credTotg = credTotg;
	}

	public Integer getNoautRg() {
		return this.noautRg;
	}

	public void setNoautRg(Integer noautRg) {
		this.noautRg = noautRg;
	}

	public Integer getNotrRg() {
		return this.notrRg;
	}

	public void setNotrRg(Integer notrRg) {
		this.notrRg = notrRg;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZoneId))
			return false;
		ZoneId castOther = (ZoneId) other;

		return ((this.getCodZone() == castOther.getCodZone()) || (this.getCodZone() != null
				&& castOther.getCodZone() != null && this.getCodZone().equals(castOther.getCodZone())))
				&& ((this.getLibZone() == castOther.getLibZone()) || (this.getLibZone() != null
						&& castOther.getLibZone() != null && this.getLibZone().equals(castOther.getLibZone())))
				&& ((this.getMatPers() == castOther.getMatPers()) || (this.getMatPers() != null
						&& castOther.getMatPers() != null && this.getMatPers().equals(castOther.getMatPers())))
				&& ((this.getNomCz() == castOther.getNomCz()) || (this.getNomCz() != null
						&& castOther.getNomCz() != null && this.getNomCz().equals(castOther.getNomCz())))
				&& ((this.getCodDr() == castOther.getCodDr()) || (this.getCodDr() != null
						&& castOther.getCodDr() != null && this.getCodDr().equals(castOther.getCodDr())))
				&& ((this.getLibDr() == castOther.getLibDr()) || (this.getLibDr() != null
						&& castOther.getLibDr() != null && this.getLibDr().equals(castOther.getLibDr())))
				&& ((this.getPrevision() == castOther.getPrevision()) || (this.getPrevision() != null
						&& castOther.getPrevision() != null && this.getPrevision().equals(castOther.getPrevision())))
				&& ((this.getPrevMb() == castOther.getPrevMb()) || (this.getPrevMb() != null
						&& castOther.getPrevMb() != null && this.getPrevMb().equals(castOther.getPrevMb())))
				&& ((this.getPrefixe() == castOther.getPrefixe()) || (this.getPrefixe() != null
						&& castOther.getPrefixe() != null && this.getPrefixe().equals(castOther.getPrefixe())))
				&& ((this.getNoFou() == castOther.getNoFou()) || (this.getNoFou() != null
						&& castOther.getNoFou() != null && this.getNoFou().equals(castOther.getNoFou())))
				&& ((this.getNolivintzv() == castOther.getNolivintzv()) || (this.getNolivintzv() != null
						&& castOther.getNolivintzv() != null && this.getNolivintzv().equals(castOther.getNolivintzv())))
				&& ((this.getNolivintzd() == castOther.getNolivintzd()) || (this.getNolivintzd() != null
						&& castOther.getNolivintzd() != null && this.getNolivintzd().equals(castOther.getNolivintzd())))
				&& ((this.getNofinFo() == castOther.getNofinFo()) || (this.getNofinFo() != null
						&& castOther.getNofinFo() != null && this.getNofinFo().equals(castOther.getNofinFo())))
				&& ((this.getNoregFo() == castOther.getNoregFo()) || (this.getNoregFo() != null
						&& castOther.getNoregFo() != null && this.getNoregFo().equals(castOther.getNoregFo())))
				&& ((this.getNofactCl() == castOther.getNofactCl()) || (this.getNofactCl() != null
						&& castOther.getNofactCl() != null && this.getNofactCl().equals(castOther.getNofactCl())))
				&& ((this.getNolivintza() == castOther.getNolivintza()) || (this.getNolivintza() != null
						&& castOther.getNolivintza() != null && this.getNolivintza().equals(castOther.getNolivintza())))
				&& ((this.getNoVil() == castOther.getNoVil()) || (this.getNoVil() != null
						&& castOther.getNoVil() != null && this.getNoVil().equals(castOther.getNoVil())))
				&& ((this.getNomAf() == castOther.getNomAf()) || (this.getNomAf() != null
						&& castOther.getNomAf() != null && this.getNomAf().equals(castOther.getNomAf())))
				&& ((this.getMatPers2() == castOther.getMatPers2()) || (this.getMatPers2() != null
						&& castOther.getMatPers2() != null && this.getMatPers2().equals(castOther.getMatPers2())))
				&& ((this.getPrefVil() == castOther.getPrefVil()) || (this.getPrefVil() != null
						&& castOther.getPrefVil() != null && this.getPrefVil().equals(castOther.getPrefVil())))
				&& ((this.getNoSect() == castOther.getNoSect()) || (this.getNoSect() != null
						&& castOther.getNoSect() != null && this.getNoSect().equals(castOther.getNoSect())))
				&& ((this.getPrefSect() == castOther.getPrefSect()) || (this.getPrefSect() != null
						&& castOther.getPrefSect() != null && this.getPrefSect().equals(castOther.getPrefSect())))
				&& ((this.getNolivpv() == castOther.getNolivpv()) || (this.getNolivpv() != null
						&& castOther.getNolivpv() != null && this.getNolivpv().equals(castOther.getNolivpv())))
				&& ((this.getBonus1() == castOther.getBonus1()) || (this.getBonus1() != null
						&& castOther.getBonus1() != null && this.getBonus1().equals(castOther.getBonus1())))
				&& ((this.getBonus2() == castOther.getBonus2()) || (this.getBonus2() != null
						&& castOther.getBonus2() != null && this.getBonus2().equals(castOther.getBonus2())))
				&& ((this.getNolivretus() == castOther.getNolivretus()) || (this.getNolivretus() != null
						&& castOther.getNolivretus() != null && this.getNolivretus().equals(castOther.getNolivretus())))
				&& ((this.getNoCodfarm() == castOther.getNoCodfarm()) || (this.getNoCodfarm() != null
						&& castOther.getNoCodfarm() != null && this.getNoCodfarm().equals(castOther.getNoCodfarm())))
				&& ((this.getNoInitz() == castOther.getNoInitz()) || (this.getNoInitz() != null
						&& castOther.getNoInitz() != null && this.getNoInitz().equals(castOther.getNoInitz())))
				&& ((this.getNbreFarm() == castOther.getNbreFarm()) || (this.getNbreFarm() != null
						&& castOther.getNbreFarm() != null && this.getNbreFarm().equals(castOther.getNbreFarm())))
				&& ((this.getSurfPrev() == castOther.getSurfPrev()) || (this.getSurfPrev() != null
						&& castOther.getSurfPrev() != null && this.getSurfPrev().equals(castOther.getSurfPrev())))
				&& ((this.getSurfReal() == castOther.getSurfReal()) || (this.getSurfReal() != null
						&& castOther.getSurfReal() != null && this.getSurfReal().equals(castOther.getSurfReal())))
				&& ((this.getCreditAnt() == castOther.getCreditAnt()) || (this.getCreditAnt() != null
						&& castOther.getCreditAnt() != null && this.getCreditAnt().equals(castOther.getCreditAnt())))
				&& ((this.getCredEchn0() == castOther.getCredEchn0()) || (this.getCredEchn0() != null
						&& castOther.getCredEchn0() != null && this.getCredEchn0().equals(castOther.getCredEchn0())))
				&& ((this.getCredEchn() == castOther.getCredEchn()) || (this.getCredEchn() != null
						&& castOther.getCredEchn() != null && this.getCredEchn().equals(castOther.getCredEchn())))
				&& ((this.getCredMat() == castOther.getCredMat()) || (this.getCredMat() != null
						&& castOther.getCredMat() != null && this.getCredMat().equals(castOther.getCredMat())))
				&& ((this.getCredTotc() == castOther.getCredTotc()) || (this.getCredTotc() != null
						&& castOther.getCredTotc() != null && this.getCredTotc().equals(castOther.getCredTotc())))
				&& ((this.getCredEchn1() == castOther.getCredEchn1()) || (this.getCredEchn1() != null
						&& castOther.getCredEchn1() != null && this.getCredEchn1().equals(castOther.getCredEchn1())))
				&& ((this.getCredTotg() == castOther.getCredTotg()) || (this.getCredTotg() != null
						&& castOther.getCredTotg() != null && this.getCredTotg().equals(castOther.getCredTotg())))
				&& ((this.getNoautRg() == castOther.getNoautRg()) || (this.getNoautRg() != null
						&& castOther.getNoautRg() != null && this.getNoautRg().equals(castOther.getNoautRg())))
				&& ((this.getNotrRg() == castOther.getNotrRg()) || (this.getNotrRg() != null
						&& castOther.getNotrRg() != null && this.getNotrRg().equals(castOther.getNotrRg())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null
						&& this.getId().equals(castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCodZone() == null ? 0 : this.getCodZone().hashCode());
		result = 37 * result + (getLibZone() == null ? 0 : this.getLibZone().hashCode());
		result = 37 * result + (getMatPers() == null ? 0 : this.getMatPers().hashCode());
		result = 37 * result + (getNomCz() == null ? 0 : this.getNomCz().hashCode());
		result = 37 * result + (getCodDr() == null ? 0 : this.getCodDr().hashCode());
		result = 37 * result + (getLibDr() == null ? 0 : this.getLibDr().hashCode());
		result = 37 * result + (getPrevision() == null ? 0 : this.getPrevision().hashCode());
		result = 37 * result + (getPrevMb() == null ? 0 : this.getPrevMb().hashCode());
		result = 37 * result + (getPrefixe() == null ? 0 : this.getPrefixe().hashCode());
		result = 37 * result + (getNoFou() == null ? 0 : this.getNoFou().hashCode());
		result = 37 * result + (getNolivintzv() == null ? 0 : this.getNolivintzv().hashCode());
		result = 37 * result + (getNolivintzd() == null ? 0 : this.getNolivintzd().hashCode());
		result = 37 * result + (getNofinFo() == null ? 0 : this.getNofinFo().hashCode());
		result = 37 * result + (getNoregFo() == null ? 0 : this.getNoregFo().hashCode());
		result = 37 * result + (getNofactCl() == null ? 0 : this.getNofactCl().hashCode());
		result = 37 * result + (getNolivintza() == null ? 0 : this.getNolivintza().hashCode());
		result = 37 * result + (getNoVil() == null ? 0 : this.getNoVil().hashCode());
		result = 37 * result + (getNomAf() == null ? 0 : this.getNomAf().hashCode());
		result = 37 * result + (getMatPers2() == null ? 0 : this.getMatPers2().hashCode());
		result = 37 * result + (getPrefVil() == null ? 0 : this.getPrefVil().hashCode());
		result = 37 * result + (getNoSect() == null ? 0 : this.getNoSect().hashCode());
		result = 37 * result + (getPrefSect() == null ? 0 : this.getPrefSect().hashCode());
		result = 37 * result + (getNolivpv() == null ? 0 : this.getNolivpv().hashCode());
		result = 37 * result + (getBonus1() == null ? 0 : this.getBonus1().hashCode());
		result = 37 * result + (getBonus2() == null ? 0 : this.getBonus2().hashCode());
		result = 37 * result + (getNolivretus() == null ? 0 : this.getNolivretus().hashCode());
		result = 37 * result + (getNoCodfarm() == null ? 0 : this.getNoCodfarm().hashCode());
		result = 37 * result + (getNoInitz() == null ? 0 : this.getNoInitz().hashCode());
		result = 37 * result + (getNbreFarm() == null ? 0 : this.getNbreFarm().hashCode());
		result = 37 * result + (getSurfPrev() == null ? 0 : this.getSurfPrev().hashCode());
		result = 37 * result + (getSurfReal() == null ? 0 : this.getSurfReal().hashCode());
		result = 37 * result + (getCreditAnt() == null ? 0 : this.getCreditAnt().hashCode());
		result = 37 * result + (getCredEchn0() == null ? 0 : this.getCredEchn0().hashCode());
		result = 37 * result + (getCredEchn() == null ? 0 : this.getCredEchn().hashCode());
		result = 37 * result + (getCredMat() == null ? 0 : this.getCredMat().hashCode());
		result = 37 * result + (getCredTotc() == null ? 0 : this.getCredTotc().hashCode());
		result = 37 * result + (getCredEchn1() == null ? 0 : this.getCredEchn1().hashCode());
		result = 37 * result + (getCredTotg() == null ? 0 : this.getCredTotg().hashCode());
		result = 37 * result + (getNoautRg() == null ? 0 : this.getNoautRg().hashCode());
		result = 37 * result + (getNotrRg() == null ? 0 : this.getNotrRg().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		return result;
	}

}
